# -*- coding: utf-8 -*-
"""PS2_nb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQ75MjZi_wXywlgDC-UyFTLQA5NJF8zY

# Cloud Counselage Machine Learning Internship Live Project

Training a ML model to suggest job role based on academic details and preferences of final year graduation students.

# Importing Libraries & Writing Helper Funcs
"""

# !pip install icecream torchmetrics optuna mlflow dagshub

import os
import pickle
import mlflow
import dagshub
import numpy as np
import optuna
import pandas as pd
import plotly
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
import plotly.io as pio
from typing import Any, Dict, Optional, Tuple, Union
from urllib.parse import urlparse
from datetime import datetime
from scipy.sparse import spmatrix
from imblearn.under_sampling import RandomUnderSampler
from mlflow import sklearn as skl
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import (
    accuracy_score,
    auc,
    average_precision_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_curve,
)
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import (
    LabelEncoder,
    MinMaxScaler,
    OneHotEncoder,
    StandardScaler,
    label_binarize,
)
from sklearn.utils.class_weight import compute_class_weight

pio.renderers.default = "colab"  # 'colab' for colab env
pio.templates.default = "seaborn"

# Function for saving plotly plots as html to embed them later
with open("html_template.html", "w") as f:
    f.write("""
  <!doctype html>
  <html>
  <head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
  <!-- <h3>{{ heading }}</h3> -->
  {{ fig }}
  </body>
  </head>
  """)


def fig_to_html(
    fig: plotly.graph_objs._figure.Figure,
    # plot_heading: str,
    output_path: str = "output.html",
    template_path: str= "html_template.html",
) -> None:
    """
    Convert a plotly figure to an HTML.
    """
    # Create output directory if it doesn't exist
    output_dir = "plotly_html"
    os.makedirs(output_dir, exist_ok=True)

    from jinja2 import Template

    # Convert the figure to HTML
    plotly_jinja_data = {
        "fig": fig.to_html(full_html=False, include_plotlyjs="cdn"),
        # "heading": plot_heading
    }

    # Load the template
    with open(os.path.join(output_dir, output_path), "w", encoding="utf-8") as f:
        with open(template_path, "r", encoding="utf-8") as template_file:
            template = Template(template_file.read())
            f.write(template.render(plotly_jinja_data))


# Plotting the Confusion Matrix
def plot_confusion_matrix(
    y_true: np.ndarray,
    y_pred: Union[np.ndarray, Tuple[np.ndarray, np.ndarray]],
    target_names: Optional[np.ndarray],
    model_name: str,
    plot_name: str,
) -> None:
    """Plot confusion matrix."""

    if isinstance(y_pred, tuple):
        y_pred = y_pred[0]

    cm = confusion_matrix(y_true, y_pred)

    fig = px.imshow(
        cm,
        text_auto=True,  # Display values on the heatmap
        labels=dict(x="Predicted", y="True"),  # Set axis labels
        x=target_names,  # Update x-axis labels
        y=target_names,  # Update y-axis labels
        color_continuous_scale="Blues",  # Customize the color scale
        width=1000,
        height=1000,
    )

    fig.update_layout(title=f"Confusion Matrix: {model_name}")  # Set plot title
    fig_to_html(fig, f"{plot_name}")
    fig.show()  # Display plot


# Plotting Precision-Recall Curve
def plot_precision_recall_curve(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    target_names: np.ndarray,
    model_name: str,
    plot_name: str,
) -> None:
    """Plot precision-recall curve."""

    # Assuming you have 'y_test' (true labels) and 'y_preds' (predicted labels)

    # 1. Binarize the labels
    n_classes = len(target_names)  # Get the number of classes
    y_true_bin: Union[np.ndarray, spmatrix] = label_binarize(y_true, classes=range(n_classes))
    y_pred_bin: Union[np.ndarray, spmatrix] = label_binarize(y_pred, classes=range(n_classes))

    # Convert to dense arrays if they are sparse matrices
    y_true_bin = np.asarray(y_true_bin)
    y_pred_bin = np.asarray(y_pred_bin)

    # 2. Create the Plotly figure
    fig = go.Figure()

    # 3. Calculate and plot precision-recall curves for each class
    for i, k in enumerate(target_names):
        precision, recall, _ = precision_recall_curve(
            y_true_bin[:, i], y_pred_bin[:, i]
        )
        avg_precision = average_precision_score(y_true_bin[:, i], y_pred_bin[:, i])

        fig.add_trace(
            go.Scatter(
                x=recall,
                y=precision,
                mode="lines",
                name=f"{k} (Avg Precision: {avg_precision:.2f})",
            )
        )

    # 4. Update layout for better visualization
    fig.update_layout(
        title=f"Precision-Recall Curve: {model_name}",
        xaxis_title="Recall",
        yaxis_title="Precision",
        xaxis_range=[0, 1],
        yaxis_range=[0, 1],
        showlegend=True,
    )

    fig_to_html(fig, f"{plot_name}")

    fig.show()  # Display plot


# Plotting ROC Curve


def plot_roc_curve(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    target_names: np.ndarray,
    model_name: str,
    plot_name: str,
) -> None:
    """Plots the ROC curve."""

    # 1. Binarize the labels.
    n_classes = len(target_names)  # Get the number of classes
    y_true_bin: Union[np.ndarray, spmatrix] = label_binarize(y_true, classes=range(n_classes))
    y_pred_bin: Union[np.ndarray, spmatrix] = label_binarize(y_pred, classes=range(n_classes))

    # Convert to dense arrays if they are sparse matrices
    y_true_bin = np.asarray(y_true_bin)
    y_pred_bin = np.asarray(y_pred_bin)

    # 2. Create the figure.
    fig = go.Figure()

    # 3. Calculate the fpr and tpr.
    for i, k in enumerate(target_names):
        fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_bin[:, i])
        roc_auc = auc(fpr, tpr)

        fig.add_trace(
            go.Scatter(x=fpr, y=tpr, mode="lines", name=f"{k} (AUC = {roc_auc:.2f})")
        )

    # 4. Update the plot.
    fig.update_layout(
        title=f"ROC Curve: {model_name}",
        xaxis_title="False Positive Rate",
        yaxis_title="True Positive Rate",
        xaxis_range=[0, 1],
        yaxis_range=[0, 1],
        showlegend=True,
    )

    fig_to_html(fig, f"{plot_name}")

    fig.show()  # Display


"""# Task
analyze the csv data and carry out all possible EDA with plotly express. extract important insights. also train logistic regession, KNN, and random forest models using make_pipeline and gridsearchcv.

Here is all the data you need:
"PS2_Dataset.csv"

## Data loading

### Subtask:
Load the dataset from the provided CSV file into a Pandas DataFrame.

**Reasoning**:
Load the dataset into a pandas DataFrame and display the first 5 rows to ensure it's loaded correctly.
"""

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
df = pd.read_csv("PS2_Dataset.csv")
# display(df.head())
print("df head:", df.head())

"""## Data exploration

### Subtask:
Explore the loaded dataset to understand its structure and characteristics.

**Reasoning**:
Explore the dataset's structure, data types, descriptive statistics, missing values, and distribution of numerical variables.
"""

# Dataset Shape
print("\nDataset Shape:", df.shape)

# Data Types
print("\nData Types:\n", df.dtypes)

# Descriptive Statistics
print("\nDescriptive Statistics:\n", df.describe())

# Missing Values
print("\nMissing Values:\n", df.isnull().sum())

# Distribution of Numerical Variables

numerical_features = df.select_dtypes(include=["number"]).columns
for feature in numerical_features:
    fig = px.histogram(df, x=feature, title=f"Distribution of {feature}")
    fig.show()

"""## Data cleaning

### Subtask:
Clean the data by handling potential outliers and inconsistencies.

**Reasoning**:
Identify potential outliers in numerical features using box plots.
"""

numerical_features = df.select_dtypes(include=["number"]).columns

for feature in numerical_features:
    fig = px.box(df, y=feature, title=f"Box Plot of {feature}")
    fig.show()

"""**Reasoning**:
Based on the box plots, we can identify potential outliers in 'Logical quotient rating', 'hackathons', and 'coding skills rating'. We will cap the outliers by replacing them with the upper and lower bounds of the IQR.


"""

df_cleaned = df.copy()

for feature in ["Logical quotient rating", "hackathons", "coding skills rating"]:
    q1 = df_cleaned[feature].quantile(0.25)
    q3 = df_cleaned[feature].quantile(0.75)
    Iqr = q3 - q1
    lower_bound = q1 - 1.5 * Iqr
    upper_bound = q3 + 1.5 * Iqr
    df_cleaned[feature] = df_cleaned[feature].clip(lower_bound, upper_bound)

# display(df_cleaned.head())
print("\ndf_cleaned:", df_cleaned.head())

"""## Data visualization

### Subtask:
Visualize the cleaned data using Plotly Express to gain insights into the distributions of variables, correlations, and potential relationships between features.

**Reasoning**:
Visualize the distribution of numerical features using histograms to understand their skewness and potential outliers.
"""

numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for feature in numerical_features:
    fig = px.histogram(df_cleaned, x=feature, title=f"Distribution of {feature}")
    fig.show()

"""**Reasoning**:
Create a correlation matrix heatmap to analyze the relationships between numerical features.


"""

correlation_matrix = df_cleaned.select_dtypes(include=["number"]).corr()
fig = ff.create_annotated_heatmap(
    z=correlation_matrix.values,
    x=list(correlation_matrix.columns),
    y=list(correlation_matrix.index),
    annotation_text=np.around(correlation_matrix.values, decimals=2),
    showscale=True,
)
fig.update_layout(title="Correlation Matrix Heatmap")
fig.show()


# Identify pairs of features with strong correlation (e.g., correlation > 0.5)
correlation_threshold = 0.5
for i in range(len(correlation_matrix.columns)):
    for j in range(i + 1, len(correlation_matrix.columns)):
        feature1 = correlation_matrix.columns[i]
        feature2 = correlation_matrix.columns[j]
        correlation = correlation_matrix.loc[feature1, feature2]
        # if abs(correlation) > correlation_threshold:
        fig = px.scatter(
            df_cleaned,
            x=feature1,
            y=feature2,
            title=f"Scatter Plot of {feature1} vs {feature2} (Correlation: {correlation:.2f})",
        )
        fig.show()

"""**Reasoning**:
Create box plots to compare the distribution of a numerical feature across different categories of a categorical feature.


"""

categorical_features = df_cleaned.select_dtypes(include=["object"]).columns
numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for categorical_feature in categorical_features:
    for numerical_feature in numerical_features:
        fig = px.box(
            df_cleaned,
            x=categorical_feature,
            y=numerical_feature,
            title=f"Box Plot of {numerical_feature} across {categorical_feature}",
        )
        fig.show()

"""**Reasoning**:
Create violin plots to visualize the distribution of a numerical feature across different categories of a categorical feature, complementing the insights from the box plots.


"""

categorical_features = df_cleaned.select_dtypes(include=["object"]).columns
numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for categorical_feature in categorical_features:
    for numerical_feature in numerical_features:
        fig = px.violin(
            df_cleaned,
            x=categorical_feature,
            y=numerical_feature,
            title=f"Violin Plot of {numerical_feature} across {categorical_feature}",
        )
        fig.show()

"""**Reasoning**:
Create a pair plot for a subset of relevant numerical features to explore the relationships and potential clusters within the data.


"""

numerical_features_subset = [
    "Logical quotient rating",
    "hackathons",
    "coding skills rating",
    "public speaking points",
]
fig = px.scatter_matrix(
    df_cleaned,
    dimensions=numerical_features_subset,
    title="Pair Plot of Selected Numerical Features",
    height=850,
)
fig.update_traces(diagonal_visible=False)
fig.show()

"""## Data analysis

### Subtask:
Analyze the visualized data to identify potential patterns, trends, and relationships between features.

**Reasoning**:
Analyze the visualized data to identify potential patterns, trends, and relationships between features, documenting the observations and insights.
"""

# Analyze the distributions of numerical features.
# Observations:
# - "Logical quotient rating", "hackathons", and "coding skills rating" show some positive skew.
# - "public speaking points" also has a slight positive skew.
# - Most participants have relatively low values for the "hackathons" feature.

# Analyze the correlation between numerical features.
# Observations:
# - "Logical quotient rating" and "coding skills rating" show a positive correlation, as expected.
# - There appears to be a weak positive correlation between "coding skills rating" and "public speaking points."
# - Other relationships between numerical variables are not strong.

# Analyze the relationship between categorical and numerical features.
# Observations:
# - The distribution of "coding skills rating" varies across different "Management or Technical" categories.
# - "Logical quotient rating" also shows slight differences across "self-learning capability?" and "worked in teams ever?".
# - "public speaking points" seems to differ across "hard/smart worker" categories.

# Analyze scatter plots for insights.
# Observations:
# - The scatter plot for "Logical quotient rating" vs. "coding skills rating" shows a positive linear trend, as expected.
# - There are no very strong non-linear relationships observed between other numerical features.

# Analyze the pair plot.
# Observations:
# - The pair plot further confirms the positive relationship between "Logical quotient rating" and "coding skills rating".
# - It indicates a possible clustering effect within the data based on different combinations of "Logical quotient rating", "hackathons", and "coding skills rating".

# Insights:
# - There is a strong positive correlation between "Logical quotient rating" and "coding skills rating", indicating that participants with higher logical quotient ratings tend to have better coding skills.
# - The different categories of "Management or Technical" have slightly different distributions for "coding skills rating", suggesting that people who have an interest in technical skills might have a better "coding skills rating".
# - Participants who self-learn seem to have better Logical quotient ratings.
# - Participants who have worked in teams may have a better "Logical quotient rating"
# - "public speaking points" appears to differ depending on the "hard/smart worker" category.
# - Possible clustering exists within the dataset based on specific combinations of numerical features.

"""## Feature engineering

### Subtask:
Prepare the data for model training by performing feature engineering steps, including encoding categorical features and potentially creating new features based on existing ones.

**Reasoning**:
Select a target variable, Identify categorical features and encode them using one-hot encoding, and split the data into training and testing sets.
"""

df_cleaned["Suggested Job Role"].unique()

df_cleaned["New Suggested Job Role"] = df_cleaned["Suggested Job Role"].replace(
    {
        "Applications Developer": "Software Development & Engineering",
        "CRM Technical Developer": "Software Development & Engineering",
        "Database Developer": "Software Development & Engineering",
        "Mobile Applications Developer": "Software Development & Engineering",
        "Software Developer": "Software Development & Engineering",
        "Software Engineer": "Software Development & Engineering",
        "Software Quality Assurance (QA) / Testing": "Software Development & Engineering",
        "Network Security Engineer": "IT Infrastructure & Security",
        "Systems Security Administrator": "IT Infrastructure & Security",
        "Technical Support": "Technical Support & User Experience",
        "UX Designer": "Technical Support & User Experience",
        "Web Developer": "Software Development & Engineering",
    }
)

print(
    "\ndf_cleaned target value counts:",
    df_cleaned["New Suggested Job Role"].value_counts(),
)

# Xt_sampled, yt_sampled = SMOTE(sampling_strategy='not majority', random_state=42).fit_resample(X_train, y_train)

# # from sklearn.preprocessing import TargetEncoder
# # tencd = TargetEncoder(target_type="multiclass", random_state=42)
# # Xt_encoded = tencd.fit_transform(X_train[categorical_features], y_train)
# # Xv_encoded = tencd.transform(X_val[categorical_features])
# # Xts_encoded = tencd.transform(X_test[categorical_features])

# # Get feature importances from the Random Forest model
# rf_model = RandomForestClassifier()
# rf_model.fit(Xt_sampled, yt_sampled)
# feature_importances = pd.Series(rf_model.feature_importances_, index=Xt_sampled.columns)

# # Sort feature importances in descending order
# feature_importances = feature_importances.sort_values(ascending=False)

# # Print the top 10 most important features
# print("Most Important Features:")
# display(feature_importances)

# Select the target variable
target_variable = "New Suggested Job Role"

# Split the data into training and testing sets
X = df_cleaned.drop(columns=[target_variable, "Suggested Job Role"])
y = df_cleaned["New Suggested Job Role"]

# Identify categorical features
# categorical_features = X.select_dtypes(include=['object']).columns

X_train, X_, y_train, y_ = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_, y_, test_size=0.5, stratify=y_, random_state=42
)

le_crts = LabelEncoder()
X_train["certifications"] = le_crts.fit_transform(X_train["certifications"])
X_val["certifications"] = le_crts.transform(X_val["certifications"])
X_test["certifications"] = le_crts.transform(X_test["certifications"])
# X['certifications'] = le_crts.fit_transform(X['certifications'])

le_wkshp = LabelEncoder()
X_train["workshops"] = le_wkshp.fit_transform(X_train["workshops"])
X_val["workshops"] = le_wkshp.transform(X_val["workshops"])
X_test["workshops"] = le_wkshp.transform(X_test["workshops"])
# X['workshops'] = le_wkshp.fit_transform(X['workshops'])

le_rwr = LabelEncoder()
X_train["reading and writing skills"] = le_rwr.fit_transform(
    X_train["reading and writing skills"]
)
X_val["reading and writing skills"] = le_rwr.transform(
    X_val["reading and writing skills"]
)
X_test["reading and writing skills"] = le_rwr.transform(
    X_test["reading and writing skills"]
)
# X['reading and writing skills'] = le_rwr.fit_transform(X['reading and writing skills'])

le_memsc = LabelEncoder()
X_train["memory capability score"] = le_memsc.fit_transform(
    X_train["memory capability score"]
)
X_val["memory capability score"] = le_memsc.transform(X_val["memory capability score"])
X_test["memory capability score"] = le_memsc.transform(
    X_test["memory capability score"]
)
# X['memory capability score'] = le_memsc.fit_transform(X['memory capability score'])

le_intsb = LabelEncoder()
X_train["Interested subjects"] = le_intsb.fit_transform(X_train["Interested subjects"])
X_val["Interested subjects"] = le_intsb.transform(X_val["Interested subjects"])
X_test["Interested subjects"] = le_intsb.transform(X_test["Interested subjects"])
# X['Interested subjects'] = le_intsb.fit_transform(X['Interested subjects'])

le_intca = LabelEncoder()
X_train["interested career area "] = le_intca.fit_transform(
    X_train["interested career area "]
)
X_val["interested career area "] = le_intca.transform(X_val["interested career area "])
X_test["interested career area "] = le_intca.transform(
    X_test["interested career area "]
)
# X['interested career area '] = le_intca.fit_transform(X['interested career area '])

le_tycompt = LabelEncoder()
X_train["Type of company want to settle in?"] = le_tycompt.fit_transform(
    X_train["Type of company want to settle in?"]
)
X_val["Type of company want to settle in?"] = le_tycompt.transform(
    X_val["Type of company want to settle in?"]
)
X_test["Type of company want to settle in?"] = le_tycompt.transform(
    X_test["Type of company want to settle in?"]
)
# X['Type of company want to settle in?'] = le_tycompt.fit_transform(X['Type of company want to settle in?'])

le_intbks = LabelEncoder()
X_train["Interested Type of Books"] = le_intbks.fit_transform(
    X_train["Interested Type of Books"]
)
X_val["Interested Type of Books"] = le_intbks.transform(
    X_val["Interested Type of Books"]
)
X_test["Interested Type of Books"] = le_intbks.transform(
    X_test["Interested Type of Books"]
)
# X['Interested Type of Books'] = le_intbks.fit_transform(X['Interested Type of Books'])

ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False, drop="if_binary")
ohe_cols = [
    "self-learning capability?",
    "Extra-courses did",
    "Taken inputs from seniors or elders",
    "Management or Technical",
    "hard/smart worker",
    "worked in teams ever?",
    "Introvert",
]

Xt_ohe = np.asarray(ohe.fit_transform(X_train[ohe_cols]))
Xv_ohe = np.asarray(ohe.transform(X_val[ohe_cols]))
Xts_ohe = np.asarray(ohe.transform(X_test[ohe_cols]))
# X_ohe = ohe.fit_transform(X[ohe_cols])

Xt_ohe = pd.DataFrame(Xt_ohe, columns=ohe.get_feature_names_out(ohe_cols))
Xv_ohe = pd.DataFrame(Xv_ohe, columns=ohe.get_feature_names_out(ohe_cols))
Xts_ohe = pd.DataFrame(Xts_ohe, columns=ohe.get_feature_names_out(ohe_cols))
# X_ohe = pd.DataFrame(X_ohe, columns=ohe.get_feature_names_out(ohe_cols))

X_train = pd.concat(
    [X_train.drop(columns=ohe_cols).reset_index(drop=True), Xt_ohe], axis=1
)
X_val = pd.concat([X_val.drop(columns=ohe_cols).reset_index(drop=True), Xv_ohe], axis=1)
X_test = pd.concat(
    [X_test.drop(columns=ohe_cols).reset_index(drop=True), Xts_ohe], axis=1
)
# X_train = pd.concat([X.drop(columns=ohe_cols).reset_index(drop=True), X_ohe], axis=1)

y_train = y_train.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)
# yn = y.reset_index(drop=True)

X_train["Technical_Inclination"] = (
    X_train["Logical quotient rating"]
    + X_train["coding skills rating"]
    + X_train["Interested subjects"]
)
X_val["Technical_Inclination"] = (
    X_val["Logical quotient rating"]
    + X_val["coding skills rating"]
    + X_val["Interested subjects"]
)
X_test["Technical_Inclination"] = (
    X_test["Logical quotient rating"]
    + X_test["coding skills rating"]
    + X_test["Interested subjects"]
)

X_train["Teamwork_Comm_Aptitude"] = (
    X_train["public speaking points"]
    + X_train["reading and writing skills"]
    + (X_train["worked in teams ever?_yes"] * 2)
)
X_val["Teamwork_Comm_Aptitude"] = (
    X_val["public speaking points"]
    + X_val["reading and writing skills"]
    + (X_val["worked in teams ever?_yes"] * 2)
)
X_test["Teamwork_Comm_Aptitude"] = (
    X_test["public speaking points"]
    + X_test["reading and writing skills"]
    + (X_test["worked in teams ever?_yes"] * 2)
)

X_train["Proactive_Learning"] = (
    (X_train["self-learning capability?_yes"] * 2)
    + (X_train["Extra-courses did_yes"] * 1.5)
    + X_train["certifications"]
    + X_train["workshops"]
)
X_val["Proactive_Learning"] = (
    (X_val["self-learning capability?_yes"] * 2)
    + (X_val["Extra-courses did_yes"] * 1.5)
    + X_val["certifications"]
    + X_val["workshops"]
)
X_test["Proactive_Learning"] = (
    (X_test["self-learning capability?_yes"] * 2)
    + (X_test["Extra-courses did_yes"] * 1.5)
    + X_test["certifications"]
    + X_test["workshops"]
)

X_train["Company_Fit"] = (
    X_train["Type of company want to settle in?"]
    + X_train["hard/smart worker_smart worker"]
)
X_val["Company_Fit"] = (
    X_val["Type of company want to settle in?"]
    + X_val["hard/smart worker_smart worker"]
)
X_test["Company_Fit"] = (
    X_test["Type of company want to settle in?"]
    + X_test["hard/smart worker_smart worker"]
)

X_train["Experience_Exposure"] = X_train["hackathons"] + X_train["coding skills rating"]
X_val["Experience_Exposure"] = X_val["hackathons"] + X_val["coding skills rating"]
X_test["Experience_Exposure"] = X_test["hackathons"] + X_test["coding skills rating"]

le_y = LabelEncoder()
y_train_encoded = le_y.fit_transform(y_train)

# Compute class weights using encoded labels
class_weights = compute_class_weight(
    class_weight="balanced", classes=np.unique(y_train_encoded), y=y_train_encoded
)

# Create dictionary with numeric indices
class_weight_dict = {idx: weight for idx, weight in enumerate(class_weights)}
# class_weight_dict[0] = class_weight_dict[0] * 1
class_weight_dict[1] = class_weight_dict[1] * 0.5
# class_weight_dict[2] = class_weight_dict[2] * 1

# Save all artifacts
artifacts_path = "assets/artifacts"
# os.makedirs(artifacts_path, exist_ok=True)
artifact_files = {
    "le_crts/le_crts.sav": le_crts,
    "le_intbks/le_intbks.sav": le_intbks,
    "le_intca/le_intca.sav": le_intca,
    "le_intsb/le_intsb.sav": le_intsb,
    "le_memsc/le_memsc.sav": le_memsc,
    "le_rwr/le_rwr.sav": le_rwr,
    "le_tycompt/le_tycompt.sav": le_tycompt,
    "le_wkshp/le_wkshp.sav": le_wkshp,
    "ohe/one_hot_encoder.sav": ohe,
    "ohe_cols/ohe_cols.sav": ohe_cols,
    "le_y/le_y.sav": le_y,
}

for filepath, obj in artifact_files.items():
    dir_path = artifacts_path + "/" + filepath.split("/")[0]
    os.makedirs(dir_path, exist_ok=True)
    full_path = os.path.join(dir_path, filepath.split("/")[1])
    # if not os.path.exists(full_path):
    #     raise FileNotFoundError(f"Artifact file not found: {full_path}")
    with open(full_path, "wb") as f:
        pickle.dump(obj, f)

df_corr = pd.DataFrame(pd.concat([X_train, pd.Series(y_train)], axis=1))
df_corr = df_corr.rename(columns={df_corr.columns[-1]: "new job roles"})

correlation_matrix = df_corr.select_dtypes(include=["number"]).corr()

# Get correlation values for the last index ('new job roles')
correlation_with_target = np.array(correlation_matrix.iloc[-1, :-1].values).reshape(1, -1)  # Reshape to 2D array
# Get feature names for x-axis labels
feature_names = correlation_matrix.columns[:-1].tolist()

fig = ff.create_annotated_heatmap(
    z=correlation_with_target,
    x=feature_names,
    y=["new job roles"],
    annotation_text=np.around(correlation_with_target, decimals=2),
    showscale=True,
    colorscale="Viridis",
)
fig.update_layout(title="Correlation of Target Variable with other Features")
fig.show()

selector = SelectKBest(chi2, k=10)
selector.fit(X_train, y_train)
selected_features = X_train.columns[selector.get_support()]
print("\nSelected Features:", selected_features)

# pd.DataFrame(data=[selector.feature_names_in_, selector.scores_], index=['Features', 'Scores']).T.sort_values(by='Scores', ascending=False)
print(
    "\nSelected Feature Scores:",
    pd.DataFrame(
        data=[selector.feature_names_in_, selector.scores_],
        index=["Features", "Scores"],
    ).T.sort_values(by="Scores", ascending=False),
)

X_train = X_train[selected_features]
print("\nX_train:", X_train)

# Xt_sampled, yt_sampled = X_train[selected_features].copy(deep=True), pd.Series(y_train.copy(deep=True))

under = RandomUnderSampler(
    sampling_strategy="majority",
    #  {
    #      'IT Infrastructure & Security': 920,
    #      'Software Development & Engineering': 920,  # Limit the majority class
    #      'Technical Support & User Experience': 920,
    #      }
    random_state=42,
    replacement=True,
)

Xt_sampled, yt_sampled = under.fit_resample(X_train, y_train) # type: ignore
print(f"\nTarget value counts: \n{yt_sampled.value_counts()}")

# Get feature importances from the Random Forest model
rf_model = RandomForestClassifier()
rf_model.fit(Xt_sampled, yt_sampled)
feature_importances = pd.Series(rf_model.feature_importances_, index=Xt_sampled.columns)

# Sort feature importances in descending order
feature_importances = feature_importances.sort_values(ascending=False)

# Print the top 10 most important features
print("\nTop 10 Most Important Features:")
# display(feature_importances)
print(feature_importances)

"""## Model Training

### Setting DAGsHub & MLFlow
"""

# dagshub.init(repo_name="ML_Projects", repo_owner="PranayJagtap06")

# from google.colab import userdata
# REPO_OWNER_ = userdata.get('REPO_OWNER')
# REPO_NAME_ = userdata.get('REPO_NAME')
# TRACKING_URI = userdata.get('MLFLOW_TRACKING_URI')

REPO_OWNER_ = os.environ.get("REPO_OWNER")
REPO_NAME_ = os.environ.get("REPO_NAME")
TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI")

os.makedirs("tmp", exist_ok=True)

# Creating function to log experiments to mlflow
dagshub.init(repo_owner=REPO_OWNER_, repo_name=REPO_NAME_, mlflow=True) # type: ignore


def create_experiment(
    experiment_name: str,
    run_name: str,
    run_metrics: Dict[str, Any],
    model,
    model_name: str = "sk_model",
    artifact_paths: Dict[str, str] = {},
    run_params: Dict[str, Any] = {},
    tag_dict: Dict[str, str] = {
        "tag1": "Linear Regression",
        "tag2": "House Rent Prediction",
    },
):
    try:
        # You can get your MLlfow tracking uri from your dagshub repo by opening "Remote" dropdown menu, go to "Experiments" tab and copy the MLflow experiment tracking uri and paste below
        mlflow.set_tracking_uri(str(TRACKING_URI))

        mlflow.set_experiment(experiment_name)

        with mlflow.start_run(run_name=run_name):
            # log params
            if run_params is not None:
                for param in run_params:
                    mlflow.log_param(param, run_params[param])

            # log metrics
            for metric, value in run_metrics.items():
                if isinstance(value, list):
                    # If the metric is a list, log each value as a separate step
                    for step, v in enumerate(value):
                        mlflow.log_metric(metric, v, step=step)
                else:
                    # If it's a single value, log it normally
                    mlflow.log_metric(metric, value)

            tracking_url_type_store = urlparse(mlflow.get_tracking_uri()).scheme

            # log artifacts
            for artifact_name, path in artifact_paths.items():
                if path and os.path.exists(path):
                    if tracking_url_type_store != "file":
                        mlflow.log_artifact(
                            path,
                            artifact_name
                        )
                elif path:
                    print(f"Warning: Artifact file not found: {path}")

            # log model
            if tracking_url_type_store != "file":
                # mlflow.sklearn.save_model(model, save_path)
                skl.log_model(model, model_name)

            mlflow.set_tags(tag_dict)

        print(f"Run - {run_name} is logged to Experiment - {experiment_name}")
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        import traceback
        traceback.print_exc()


"""### Optuna"""


# Define the evaluation function
def evaluate_model(y_true: Any, y_pred: Any) -> Tuple[float, float, float, float, float, float]:
    # y_true = np.asarray(y_true)
    # y_pred = np.asarray(y_pred)
    accuracy = float(accuracy_score(y_true, y_pred))
    precision = float(precision_score(y_true, y_pred, average="macro"))
    recall = float(recall_score(y_true, y_pred, average="macro"))
    balanced_acc = balanced_accuracy_score(y_true, y_pred)
    mcc = matthews_corrcoef(y_true, y_pred)
    f1 = float(f1_score(y_true, y_pred, average="macro"))
    return accuracy, precision, recall, balanced_acc, mcc, f1


# Random Forest with Optuna
def objective_rf(trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 500),
        "max_depth": trial.suggest_int("max_depth", 20, 60),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2"]),
        "min_samples_split": trial.suggest_int("min_samples_split", 20, 50),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 20, 50),
        "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        "class_weight": trial.suggest_categorical(
            "class_weight", ["balanced_subsample", "balanced"]
        ),
        # 'class_weight': class_weight_dict,
        "random_state": 42,
        "n_jobs": -1,
    }

    # Use stratified k-fold CV
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

    pipeline = make_pipeline(
        # StandardScaler(),
        MinMaxScaler(),
        RandomForestClassifier(**params),
    )

    # Calculate cross-validation score (accuracy)
    scores = []
    for train_idx, val_idx in cv.split(Xt_sampled.to_numpy(), yt_sampled):
        X_fold_train, X_fold_val = Xt_sampled[train_idx], Xt_sampled[val_idx]
        y_fold_train, y_fold_val = (
            yt_sampled[train_idx],
            yt_sampled[val_idx],
        )

        pipeline.fit(X_fold_train, y_fold_train)
        y_pred = pipeline.predict(X_fold_val)
        # fold_f1 = f1_score(y_fold_val, y_pred, average='macro')
        _, _, _, accuracy, _, _ = evaluate_model(y_fold_val.to_numpy(), y_pred)
        scores.append(accuracy)

    # pipeline.fit(Xt_sampled, yn)
    # y_pred = pipeline.predict(X_val)
    # _, _, _, accuracy, _, _ = evaluate_model(y_val, y_pred)

    return float(np.mean(scores))  # Return the mean accuracy across folds
    # return accuracy


# Run optimization for each model
np.random.seed(42)
study_rf = optuna.create_study(direction="maximize")
study_rf.optimize(objective_rf, n_trials=20, n_jobs=-1)

best_params3 = study_rf.trials_dataframe().sort_values(ascending=False, by="value")

# Random Forest
best_rf = make_pipeline(
    StandardScaler(),
    RandomForestClassifier(
        n_estimators=best_params3.iloc[0]["params_n_estimators"],
        max_depth=best_params3.iloc[0]["params_max_depth"],
        max_features=best_params3.iloc[0]["params_max_features"],
        min_samples_split=best_params3.iloc[0]["params_min_samples_split"],
        min_samples_leaf=best_params3.iloc[0]["params_min_samples_leaf"],
        bootstrap=best_params3.iloc[0]["params_bootstrap"],
        class_weight=best_params3.iloc[0]["params_class_weight"],
        # class_weight=class_weight_dict,
        random_state=42,
        n_jobs=-1,
    ),
)

Xv = X_val[selected_features]
best_rf.fit(Xt_sampled, yt_sampled)
print("\n\nRandom Forest Classifier | Training:")
print(f"Train set Score: {best_rf.score(Xt_sampled, yt_sampled):.4f}")
print(f"Val set Score: {best_rf.score(Xv, y_val):.4f}")
y_train_rf = best_rf.predict(Xt_sampled)
y_pred_rf = best_rf.predict(Xv)

(
    train_accuracy_rf,
    train_precision_rf,
    train_recall_rf,
    train_bacc_rf,
    train_mcc_rf,
    train_f1_rf,
) = evaluate_model(yt_sampled, y_train_rf)
val_accuracy_rf, val_precision_rf, val_recall_rf, val_bacc_rf, val_mcc_rf, val_f1_rf = (
    evaluate_model(y_val, y_pred_rf)
)

# print("Random Forest Classifier:")
print(f"Best parameters: {study_rf.best_params}")
print(
    f"Train | Accuracy: {train_accuracy_rf:.4f}, Precision: {train_precision_rf:.4f}, Recall: {train_recall_rf:.4f}, Balance Acc: {train_bacc_rf:.4f}, MCC: {train_mcc_rf:.4f}, F1-score: {train_f1_rf:.4f}"
)
print(
    f"Val | Accuracy: {val_accuracy_rf:.4f}, Precision: {val_precision_rf:.4f}, Recall: {val_recall_rf:.4f}, Balance Acc: {val_bacc_rf:.4f}, MCC: {val_mcc_rf:.4f}, F1-score: {val_f1_rf:.4f}"
)

print(
    f"\nTrain | Classification Report for Random Forest Classifier:\n{classification_report(yt_sampled, y_train_rf, target_names=np.unique(yt_sampled))}"
)
print(
    f"\nVal | Classification Report for Random Forest Classifier:\n{classification_report(y_val, y_pred_rf, target_names=np.unique(yt_sampled))}"
)

plot_confusion_matrix(
    y_val,
    y_pred_rf,
    target_names=le_y.classes_,
    model_name="MulticlassClassifier",
    plot_name="jrs_val_cm.html",
)

plot_precision_recall_curve(
    np.asarray(le_y.transform(y_val)),
    np.asarray(le_y.transform(y_pred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_val_prcurve.html",
)

plot_roc_curve(
    np.asarray(le_y.transform(y_val)),
    np.asarray(le_y.transform(y_pred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_val_roccurve.html",
)

Xts = X_test[selected_features]
y_tspred_rf = best_rf.predict(Xts)
(
    test_accuracy_rf,
    test_precision_rf,
    test_recall_rf,
    test_bacc_rf,
    test_mcc_rf,
    test_f1_rf,
) = evaluate_model(y_test, y_tspred_rf)

print("Random Forest Classifier | Testing:")
print(f"Best parameters: {study_rf.best_params}")
print(
    f"Train | Accuracy: {train_accuracy_rf:.4f}, Precision: {train_precision_rf:.4f}, Recall: {train_recall_rf:.4f}, Balance Acc: {train_bacc_rf:.4f}, MCC: {train_mcc_rf:.4f}, F1-score: {train_f1_rf:.4f}"
)
print(
    f"Test | Accuracy: {test_accuracy_rf:.4f}, Precision: {test_precision_rf:.4f}, Recall: {test_recall_rf:.4f}, Balance Acc: {test_bacc_rf:.4f}, MCC: {test_mcc_rf:.4f}, F1-score: {test_f1_rf:.4f}"
)

print(
    f"\nTrain | Classification Report for Random Forest Classifier:\n{classification_report(yt_sampled, y_train_rf, target_names=np.unique(y))}"
)
print(
    f"\nTest | Classification Report for Random Forest Classifier:\n{classification_report(y_test, y_tspred_rf, target_names=np.unique(y))}"
)

plot_confusion_matrix(
    y_test,
    y_tspred_rf,
    target_names=le_y.classes_,
    model_name="MulticlassClassifier",
    plot_name="jrs_test_cm.html",
)

plot_precision_recall_curve(
    np.asarray(le_y.transform(y_test)),
    np.asarray(le_y.transform(y_tspred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_test_prcurve.html",
)

plot_roc_curve(
    np.asarray(le_y.transform(y_test)),
    np.asarray(le_y.transform(y_tspred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_test_roccurve.html",
)

"""#### Logging Experiment"""

# Logging Experiment

experiment_name = "job_role_suggestion"
run_name = "run_" + str(datetime.now().strftime("%d-%m-%y_%H:%M:%S"))

run_metrics = {
    "train_acc": train_accuracy_rf,
    "test_acc": test_accuracy_rf,
    "train_precision": train_precision_rf,
    "test_precision": test_precision_rf,
    "train_recall": train_recall_rf,
    "test_recall": test_recall_rf,
    "train_f1": train_f1_rf,
    "test_f1": test_f1_rf,
    "train_bal_acc": train_bacc_rf,
    "test_bal_acc": test_bacc_rf,
    "train_mcc": train_mcc_rf,
    "test_mcc": test_mcc_rf,
    "val_acc": val_accuracy_rf,
    "val_precision": val_precision_rf,
    "val_recall": val_recall_rf,
    "val_bal_acc": val_bacc_rf,
    "val_mcc": val_mcc_rf,
    "val_f1": val_f1_rf,
}

artifact_paths = {
    "le_crts": "assets/artifacts/le_crts/le_crts.sav",
    "le_intbks": "assets/artifacts/le_intbks/le_intbks.sav",
    "le_intca": "assets/artifacts/le_intca/le_intca.sav",
    "le_intsb": "assets/artifacts/le_intsb/le_intsb.sav",
    "le_memsc": "assets/artifacts/le_memsc/le_memsc.sav",
    "le_rwr": "assets/artifacts/le_rwr/le_rwr.sav",
    "le_tycompt": "assets/artifacts/le_tycompt/le_tycompt.sav",
    "le_wkshp": "assets/artifacts/le_wkshp/le_wkshp.sav",
    "ohe": "assets/artifacts/ohe/one_hot_encoder.sav",
    "ohe_cols": "assets/artifacts/ohe_cols/ohe_cols.sav",
    "le_y": "assets/artifacts/le_y/le_y.sav",
    "val_cm": "plotly_html/jrs_val_cm.html",
    "val_prcurve": "plotly_html/jrs_val_prcurve.html",
    "val_roccurve": "plotly_html/jrs_val_roccurve.html",
    "test_cm": "plotly_html/jrs_test_cm.html",
    "test_prcurve": "plotly_html/jrs_test_prcurve.html",
    "test_roccurve": "plotly_html/jrs_test_roccurve.html",
}

run_params = study_rf.best_params

create_experiment(
    experiment_name,
    run_name,
    run_metrics,
    best_rf,
    model_name="job_role_rf",
    artifact_paths=artifact_paths,
    run_params=run_params,
    tag_dict={"tag1": "Random Forest Classifier", "tag2": "Job Role Suggestion"},
)

"""### NN Model"""

# le_y = LabelEncoder()
# nny_train = le_y.fit_transform(yt_sampled)
# nny_val = le_y.transform(y_val)
# nny_test = le_y.transform(y_test)

# np.save('x_train.npy', Xt_sampled, allow_pickle=True)
# np.save('y_train.npy', nny_train, allow_pickle=True)
# np.save('x_val.npy', X_val, allow_pickle=True)
# np.save('y_val.npy', nny_val, allow_pickle=True)
# np.save('x_test.npy', X_test, allow_pickle=True)
# np.save('y_test.npy', nny_test, allow_pickle=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model_builder.py
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
#
#
# class MulticlassClassifier_(nn.Module):
#     def __init__(self, classes_num: int, in_features: int=19, hidden_layers: list[int]=[256, 128, 64, 16]) -> None:
#         super().__init__()
#         fp2, fp3, fp4, fp5 = hidden_layers
#         self.fp1 = nn.Linear(in_features, fp2)
#         self.bn1 = nn.BatchNorm1d(fp2)
#         self.fp2 = nn.Linear(fp2, fp3)
#         self.bn2 = nn.BatchNorm1d(fp3)
#         self.fp3 = nn.Linear(fp3, fp4)
#         self.bn3 = nn.BatchNorm1d(fp4)
#         self.fp4 = nn.Linear(fp4, fp5)
#         self.bn4 = nn.BatchNorm1d(fp5)
#         self.fp5 = nn.Linear(fp5, classes_num)
#         self.pool = nn.AvgPool1d(kernel_size=1, stride=1)
#         self.dropout = nn.Dropout(0.3)
#
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         x = F.relu(self.bn1(self.fp1(x)))
#         x = self.dropout(x)
#         x = F.relu(self.bn2(self.fp2(x)))
#         x = self.dropout(x)
#         x = F.relu(self.bn3(self.fp3(x)))
#         x = self.dropout(x)
#         x = self.pool(self.bn4(self.fp4(x)))
# #         x = x.view(-1, 1)
#         x = self.fp5(x)
#         return x.squeeze(1)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data_loader.py
# import os
# import torchvision
# import torch
# import numpy as np
# import pandas as pd
# import torch.nn as nn
# from model_builder import MulticlassClassifier_
# from typing import Dict, List, Optional, Tuple
# from dataclasses import dataclass, field
# from torchvision import datasets, transforms
# from torch.utils.data import DataLoader
# from torch.utils.data import WeightedRandomSampler
# from torch.utils.data.distributed import DistributedSampler
# from sklearn.utils.class_weight import compute_class_weight
#
# NUM_WORKERS = os.cpu_count()
#
#
# class CreateDataset_(torch.utils.data.Dataset):
#     def __init__(self, X: np.ndarray, y: np.ndarray) -> None:
#         assert len(X) == len(y), "X and y must have the same length"
#         self.x = torch.from_numpy(X).float()
#         self.y = torch.from_numpy(y).long()
#
#     def __len__(self) -> int:
#         return len(self.x)
#
#     def __getitem__(self, idx) -> Tuple[torch.Tensor, torch.Tensor]:
#         if idx >= len(self.x):
#             raise IndexError(f"Index {idx} is out of bounds for dimension 0 with size {len(self.x)}")
#         return self.x[idx], self.y[idx]
#
#
# def load_data_objs(
#     batch_size: int,
#     rank: int,
#     world_size: int,
#     epochs: int,
#     in_features: int,
#     x_train_path: str,
#     y_train_path: str,
#     x_val_path: str,
#     y_val_path: str,
#     use_gpu: bool,
#     gpu_id: int,
#     learning_rate: float,
#     num_workers: int = NUM_WORKERS,
#     # lr_scheduler: Optional[str] = None,
# ) -> tuple[DataLoader, DataLoader, nn.Module, nn.CrossEntropyLoss, torch.optim.Optimizer]:
#     train_dts = CreateDataset_(np.load(x_train_path, allow_pickle=True), np.load(y_train_path, allow_pickle=True))
#     val_dts = CreateDataset_(np.load(x_val_path, allow_pickle=True), np.load(y_val_path, allow_pickle=True))
#
#     model = MulticlassClassifier_(in_features=in_features, classes_num=len(train_dts.y.unique()))
#
#     if use_gpu:
#         dist_sampler_train = DistributedSampler(train_dts, num_replicas=world_size, rank=rank, seed=42)
#         train_dtl = DataLoader(train_dts, batch_size=batch_size, shuffle=False, pin_memory=True, sampler=dist_sampler_train, num_workers=num_workers, )
#
#         dist_sampler_val = DistributedSampler(val_dts, num_replicas=world_size, rank=rank, seed=42)
#         val_dtl = DataLoader(val_dts, batch_size=1, shuffle=False, pin_memory=True, sampler=dist_sampler_val, num_workers=num_workers, )
#
#     else:
#         train_dtl = DataLoader(train_dts, batch_size=batch_size, shuffle=True, pin_memory=True, num_workers=num_workers, )
#
#         val_dtl = DataLoader(val_dts, batch_size=1, shuffle=False, pin_memory=True, num_workers=num_workers, )
#
#     optimizer = torch.optim.Adam(
#         params=model.parameters(), lr=learning_rate, weight_decay=1e-4)
#
#     criterion = nn.CrossEntropyLoss()
#
#     # scheduler = None
#     # if lr_scheduler:
#     #     LR_SCHEDULER = {
#     #         # requires to set metric
#     #         "reduce_lr": torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2),
#     #         "one_cycle_lr": torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=0.01, epochs=epochs, steps_per_epoch=len(train_dtl), anneal_strategy='cos')
#     #     }
#
#     #     if lr_scheduler in LR_SCHEDULER:
#     #         scheduler = LR_SCHEDULER[lr_scheduler]
#     #     else:
#     #         raise ValueError(f"""Invalid lr_scheduler value: {
#     #             lr_scheduler}. Valid options are: {list(LR_SCHEDULER.keys())}""")
#
#     return train_dtl, val_dtl, model, criterion, optimizer

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pt_engine.py
# from torch.nn.parallel import DistributedDataParallel as DDP
# from torch.utils.data import DataLoader
# from typing import List, Dict, Optional, Tuple
# from rich.progress import track
# from pathlib import Path
# from icecream import ic
# import torch.distributed as dist
# import torch.nn.functional as F
# import torch.optim as optim
# import torch.nn as nn
# import numpy as np
# import random
# import torchmetrics
# import torch
# import time
# import os
#
#
# def set_seed(seed):
#     random.seed(seed)
#     np.random.seed(seed)
#     torch.manual_seed(seed)
#     if torch.cuda.is_available():
#         torch.cuda.manual_seed(seed)
#         torch.cuda.manual_seed_all(seed)
#
#
# def loss_metric_tensor(array: List[Dict[str, np.ndarray]]) -> torch.Tensor:
#     all_tensors = [torch.tensor([[array[0][j][k] for k in range(
#         len(array[0][j]))]], dtype=torch.float32) for j in array[0].keys()]
#     b = torch.cat(all_tensors, dim=0)
#     return b.transpose(0, 1)
#
#
# class CustomTrainer:
#     def __init__(
#         self,
#         model: nn.Module,
#         train_data: DataLoader,
#         val_data: DataLoader,
#         criterion: nn.CrossEntropyLoss,
#         optimizer: torch.optim.Optimizer,
#         gpu_id: int,
#         save_path: str | Path,
#         use_gpu: bool,
#         patience: int = 5,
#         max_epochs: int = 10,
#         world_size: int = 1,
#         lr_scheduler: Optional[str] = None
#         ) -> None:
#         self.model = model
#         self.train_data = train_data
#         self.val_data = val_data
#         self.classes_num = len(train_data.dataset.y.unique())
#         self.criterion = criterion
#         self.optimizer = optimizer
#         self.gpu_id = gpu_id
#         self.save_path = save_path
#         self.use_gpu = use_gpu
#         self.patience = patience
#         self.max_epochs = max_epochs
#         self.world_size = world_size
#         self.lr_scheduler = lr_scheduler
#         self.scheduler = self._create_scheduler()
#
#         if self.use_gpu:
#             if self.gpu_id is None:
#                 raise ValueError("gpu_id must be specified when using GPU.")
#             self.model = DDP(self.model.to(self.gpu_id), device_ids=[self.gpu_id])
#
#         self._setup_metrics()
#         self._init_history()
#
#
#     def _create_scheduler(self) -> Optional[torch.optim.lr_scheduler._LRScheduler]:
#         """Create a learning rate scheduler based on the configuration."""
#         if self.lr_scheduler:
#             if self.lr_scheduler == "reduce_lr":
#                 scheduler = optim.lr_scheduler.ReduceLROnPlateau(
#                     self.optimizer, mode="min", factor=0.5, patience=2
#                 )
#             elif self.lr_scheduler == "one_cycle_lr":
#                 scheduler = optim.lr_scheduler.OneCycleLR(
#                     self.optimizer,
#                     max_lr=0.01,
#                     epochs=self.config.max_epochs,
#                     steps_per_epoch=len(self.train_data),
#                     anneal_strategy="cos",
#                 )
#             else:
#                 raise ValueError(
#                     f"Invalid lr_scheduler value: {self.lr_scheduler}. "
#                     "Valid options are: reduce_lr, one_cycle_lr"
#                 )
#             return scheduler
#         return None
#
#     def _setup_metrics(self) -> None:
#         if self.use_gpu:
#             self.train_metric_accuracy = torchmetrics.classification.MulticlassAccuracy(num_classes=self.classes_num, average="micro", sync_on_compute=False).to(self.gpu_id)
#             self.train_metric_f1score = torchmetrics.classification.MulticlassF1Score(num_classes=self.classes_num, average="macro", sync_on_compute=False).to(self.gpu_id)
#             self.val_metric_accuracy = torchmetrics.classification.MulticlassAccuracy(num_classes=self.classes_num, average="micro", sync_on_compute=False).to(self.gpu_id)
#             self.val_metric_f1score = torchmetrics.classification.MulticlassF1Score(num_classes=self.classes_num, average="macro", sync_on_compute=False).to(self.gpu_id)
#         else:
#             self.train_metric_accuracy = torchmetrics.classification.MulticlassAccuracy(num_classes=self.classes_num, average="micro")
#             self.train_metric_f1score = torchmetrics.classification.MulticlassF1Score(num_classes=self.classes_num, average="macro")
#             self.val_metric_accuracy = torchmetrics.classification.MulticlassAccuracy(num_classes=self.classes_num, average="micro")
#             self.val_metric_f1score = torchmetrics.classification.MulticlassF1Score(num_classes=self.classes_num, average="macro")
#
#
#     def _init_history(self) -> None:
#         if self.use_gpu:
#             self.train_losses_ = [{f'train_losses{i}': np.array([]) for i in range(self.world_size)}]
#             self.val_losses_ = [{f'val_losses{i}': np.array([]) for i in range(self.world_size)}]
#             self.train_f1s_ = [{f'train_metrics{i}': np.array([]) for i in range(self.world_size)}]
#             self.val_f1s_ = [{f'val_metrics{i}': np.array([]) for i in range(self.world_size)}]
#             self.train_accuracies_ = [{f'train_metrics{i}': np.array([]) for i in range(self.world_size)}]
#             self.val_accuracies_ = [{f'val_metrics{i}': np.array([]) for i in range(self.world_size)}]
#         else:
#             self.train_losses_ = [{"losses": np.array([])}]
#             self.val_losses_ = [{"losses": np.array([])}]
#             self.train_f1s_ = [{"metrics": np.array([])}]
#             self.val_f1s_ = [{"metrics": np.array([])}]
#             self.train_accuracies_ = [{"metrics": np.array([])}]
#             self.val_accuracies_ = [{"metrics": np.array([])}]
#
#
#     def _run_batch(self, source: torch.Tensor, targets: torch.Tensor, pred_labels: np.ndarray) -> tuple[float]:
#         source = source.to(self.gpu_id)
#         targets = targets.to(self.gpu_id)
#
#         self.model.train()
#         self.optimizer.zero_grad()
#         y_logits = self.model(source)
#         preds = torch.softmax(y_logits, dim=1)
#         preds = torch.argmax(preds, dim=1)
#         loss = self.criterion(y_logits, targets)
#         loss.backward()
#         self.optimizer.step()
#
#         pred_labels[0]['preds'].extend(preds.detach().cpu().numpy().tolist())
#         pred_labels[0]['targets'].extend(targets.cpu().numpy().tolist())
#
#         self.train_metric_accuracy.update(preds, targets)
#         self.train_metric_f1score.update(preds, targets)
#
#         return loss.item(), pred_labels
#
#
#     def _run_eval(self, epoch: int) -> Tuple[float, float, float, np.ndarray]:
#         self.model.eval()
#         total_samples = len(self.val_data.dataset)
#         total_loss = 0
#         total_samples_ = 0
#
#         if self.use_gpu:
#             self.val_data.sampler.set_epoch(epoch)
#             self.val_metric_accuracy.reset()
#             self.val_metric_f1score.reset()
#
#         pred_labels = np.array([{'targets': [], 'preds': []}])
#         with torch.inference_mode():
#             for source, targets in track(self.val_data, description=f"Evaluating...", style='red', complete_style='cyan', finished_style='green'):
#                 source = source.to(self.gpu_id)
#                 targets = targets.to(self.gpu_id)
#
#                 y_logits = self.model(source)
#                 preds = torch.softmax(y_logits, dim=1)
#                 preds = torch.argmax(preds, dim=1)
#                 loss = self.criterion(y_logits, targets)
#
#                 batch_size_ = source.size(0)  # Get batch size
#                 total_samples_ += batch_size_  # Accumulate total samples
#
#                 self.val_metric_accuracy.update(preds, targets)
#                 self.val_metric_f1score.update(preds, targets)
#                 total_loss += loss.item() * batch_size_
#
#                 pred_labels[0]['preds'].extend(preds.detach().cpu().numpy().tolist())
#                 pred_labels[0]['targets'].extend(targets.cpu().numpy().tolist())
#
#         self.model.train()
#         avg_loss = total_loss / total_samples_
#
#         accuracy = self.val_metric_accuracy.compute()
#         f1score = self.val_metric_f1score.compute()
#
#         return avg_loss, accuracy.item(), f1score.item(), pred_labels
#
#
#     def _run_epoch(self, epoch: int, total_epochs: int) -> tuple[float, float, float, np.ndarray]:
#         total_samples = len(self.train_data.dataset)
#         num_batches = len(self.train_data)
#         total_loss = 0
#         total_samples_ = 0
#
#         if self.use_gpu:
#             self.train_data.sampler.set_epoch(epoch)
#             self.train_metric_accuracy.reset()
#             self.train_metric_f1score.reset()
#
#         pred_labels = np.array([{'targets': [], 'preds': []}])
#         for source, targets in track(self.train_data,
#                          description=f"""{f"[GPU{self.gpu_id}] " if self.use_gpu else ""}Epoch {epoch + 1}/{total_epochs} | Training: {num_batches} batches...""", style='red', complete_style='cyan', finished_style='green'):
#
#             batch_size_ = source.size(0)  # Get batch size
#             total_samples_ += batch_size_  # Accumulate total samples
#
#             loss, pred_labels = self._run_batch(source, targets, pred_labels)
#             total_loss += loss * batch_size_
#
#         avg_loss = total_loss / total_samples_
#
#         accuracy = self.train_metric_accuracy.compute()
#         f1score = self.train_metric_f1score.compute()
#
#         return avg_loss, accuracy.item(), f1score.item(), pred_labels
#
#
#     def _save_checkpoint(self, epoch: int, train_loss: float, val_loss: float, train_accuracy: float, val_accuracy: float, train_f1score: float, val_f1score: float, train_labels: np.ndarray, val_labels: np.ndarray) -> None:
#         model_state = self.model.module.state_dict() if isinstance(self.model, DDP) else self.model.state_dict()
#         ckp = {
#             'epoch': epoch,
#             'model_state_dict': model_state,
#             'optimizer_state_dict': self.optimizer.state_dict(),
#             'train_loss': train_loss,
#             'val_loss': val_loss,
#             'train_accuracy': train_accuracy,
#             'val_accuracy': val_accuracy,
#             'train_f1score': train_f1score,
#             'val_f1score': val_f1score,
#             }
#         ckp_path = f"{self.save_path}/best_model.pt"
#         torch.save(ckp, ckp_path)
#         np.save("loss_train.npy", train_loss, allow_pickle=True)
#         np.save("accuracy_train.npy", train_accuracy, allow_pickle=True)
#         np.save("f1score_train.npy", train_f1score, allow_pickle=True)
#         np.save("train_labels.npy", train_labels, allow_pickle=True)
#         np.save("loss_val.npy", val_loss, allow_pickle=True)
#         np.save("accuracy_val.npy", val_accuracy, allow_pickle=True)
#         np.save("f1score_val.npy", val_f1score, allow_pickle=True)
#         np.save("val_labels.npy", val_labels, allow_pickle=True)
#
#         print(f"\t\tNew best model saved at {ckp_path} {f'from GPU{self.gpu_id} |' if self.use_gpu else ''} epoch {epoch+1}.")
#
#
#     def gather_tensor(self, t: torch.Tensor) -> torch.Tensor:
#         gathered_t = [torch.zeros_like(t) for _ in range(self.world_size)]
#         torch.distributed.all_gather(gathered_t, t)
#         return torch.cat(gathered_t, dim=0)
#
#
#     def train(self) -> None:
#         if self.use_gpu:
#             should_stop = torch.zeros(1).to(self.gpu_id)
#             patience_count = torch.zeros(1, dtype=torch.int32).to(self.gpu_id)
#
#             # Gather losses from all GPUs
#             train_losses = [torch.zeros(1).to(self.gpu_id)
#                             for _ in range(self.world_size)]
#             val_losses = [torch.zeros(1).to(self.gpu_id)
#                           for _ in range(self.world_size)]
#             train_f1s = [torch.zeros(1).to(self.gpu_id)
#                          for _ in range(self.world_size)]
#             val_f1s = [torch.zeros(1).to(self.gpu_id)
#                        for _ in range(self.world_size)]
#             train_accuracies = [torch.zeros(1).to(self.gpu_id)
#                                 for _ in range(self.world_size)]
#             val_accuracies = [torch.zeros(1).to(self.gpu_id)
#                               for _ in range(self.world_size)]
#             val_losses_t = torch.empty(0).to(self.gpu_id)
#             val_metrics_t = torch.empty(0).to(self.gpu_id)
#         else:
#             should_stop = torch.zeros(1)
#             patience_count = torch.zeros(1, dtype=torch.int32)
#             train_losses = []
#             val_losses = []
#             train_f1s = []
#             val_f1s = []
#             train_accuracies = []
#             val_accuracies = []
#             val_losses_t = []
#             val_metrics_t = []
#
#         set_seed(42)
#         best_val_loss = float('inf')
#         best_val_f1 = 0.0
#
#         for epoch in range(self.max_epochs):
#             train_loss, train_accuracy, train_f1, train_labels = self._run_epoch(epoch, self.max_epochs)
#             val_loss, val_accuracy, val_f1, val_labels = self._run_eval(epoch)
#
#             print(f"""\t{f"[GPU{self.gpu_id}] | " if self.use_gpu else ""}Batches: {len(self.train_data)} per GPU | Val Steps: {len(self.val_data)} | train_loss: {train_loss:.4f} | val_loss: {val_loss:.4f} | train_accuracy: {train_accuracy:.4f} | val_accuracy: {val_accuracy:.4f} | train_f1: {train_f1:.4f} | val_f1: {val_f1:.4f} | Learning Rate: {self.optimizer.param_groups[0]['lr']:.6f}""")
#
#             if self.scheduler is not None:
#                 self.scheduler.step(val_loss)
#
#             # ic(pred_labels[0]['targets'][-6:], pred_labels[0]['preds'][-6:])
#
#             # Save losses for all GPUs
#             if self.use_gpu:
#                 try:
#                     torch.distributed.all_gather(
#                         train_losses, torch.tensor([train_loss]).to(self.gpu_id))
#                     torch.distributed.all_gather(
#                         val_losses, torch.tensor([val_loss]).to(self.gpu_id))
#                     torch.distributed.all_gather(
#                         train_f1s, torch.tensor([train_f1]).to(self.gpu_id))
#                     torch.distributed.all_gather(
#                         val_f1s, torch.tensor([val_f1]).to(self.gpu_id))
#                     torch.distributed.all_gather(
#                         train_accuracies, torch.tensor([train_accuracy]).to(self.gpu_id))
#                     torch.distributed.all_gather(
#                         val_accuracies, torch.tensor([val_accuracy]).to(self.gpu_id))
#                 except RuntimeError as e:
#                     print(f"Error gathering losses: {e}")
#                     break
#
#                 for i in range(self.world_size):
#                     self.train_losses_[0][f"train_losses{i}"] = np.append(
#                         self.train_losses_[0][f"train_losses{i}"], train_losses[i].item())
#                     self.val_losses_[0][f"val_losses{i}"] = np.append(
#                         self.val_losses_[0][f"val_losses{i}"], val_losses[i].item())
#                     self.train_f1s_[0][f"train_metrics{i}"] = np.append(
#                         self.train_f1s_[0][f"train_metrics{i}"], train_f1s[i].item())
#                     self.val_f1s_[0][f"val_metrics{i}"] = np.append(
#                         self.val_f1s_[0][f"val_metrics{i}"], val_f1s[i].item())
#                     self.train_accuracies_[0][f"train_metrics{i}"] = np.append(
#                         self.train_accuracies_[0][f"train_metrics{i}"], train_accuracies[i].item())
#                     self.val_accuracies_[0][f"val_metrics{i}"] = np.append(
#                         self.val_accuracies_[0][f"val_metrics{i}"], val_accuracies[i].item())
#
#                 val_losses_t = loss_metric_tensor(self.val_losses_)
#                 val_metrics_t = loss_metric_tensor(self.val_f1s_)
#
#                 val_losses_last_item = np.min(val_losses_t[-1:].squeeze().numpy())
#                 val_metrics_last_item = np.max(val_metrics_t[-1:].squeeze().numpy())
#                 bval_loss = np.min(val_losses_t.numpy())
#                 bval_metric = np.max(val_metrics_t.numpy())
#
#                 improved = torch.tensor([False], dtype=torch.bool).to(self.gpu_id)
#             else:
#                 self.val_losses_[0]["losses"] = np.append(self.val_losses_[0]["losses"], val_losses)
#                 self.val_f1s_[0]["metrics"] = np.append(self.val_f1_s[0]["metrics"], val_f1s)
#                 self.val_accuracies_[0]["metrics"] = np.append(self.val_accuracies_[0]["metrics"], val_accuracies)
#
#                 val_losses_last_item = self.val_losses_[0]["losses"][-1]
#                 val_metrics_last_item = self.val_f1s_[0]["metrics"][-1]
#                 bval_loss = np.min(self.val_losses_)
#                 bval_metric = np.max(self.val_f1s_)
#                 improved = torch.tensor([False], dtype=torch.bool)
#
#             if self.use_gpu:
#                 if (len(torch.where(val_losses_t == val_losses_last_item)[1]) == 1) and (
#                         len(torch.where(val_metrics_t == val_metrics_last_item)[1]) == 1):
#                     val_losses_last_gpu = torch.where(
#                         val_losses_t == val_losses_last_item)[1].item()
#                     val_metrics_last_gpu = torch.where(
#                         val_metrics_t == val_metrics_last_item)[1].item()
#                     val_losses_last_gpu_row = torch.where(
#                         val_losses_t == val_losses_last_item)[0].item()
#                     val_metrics_last_gpu_row = torch.where(
#                         val_metrics_t == val_metrics_last_item)[0].item()
#
#                     val_losses_last_metric = val_metrics_t[val_losses_last_gpu_row, val_losses_last_gpu]
#                     val_metrics_last_loss = val_losses_t[val_metrics_last_gpu_row, val_metrics_last_gpu]
#
#                     if (val_losses_last_item == bval_loss) and (val_metrics_last_item == bval_metric) and (
#                             val_losses_last_gpu == val_metrics_last_gpu) and (self.gpu_id == val_losses_last_gpu):
#                         print(f"""\t\t1/1:[GPU{self.gpu_id}] val_loss improved to {
#                         val_losses_last_item:.4f} | val_f1score improved to {val_metrics_last_item:.4f}""")
#                         self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                         improved = torch.tensor([True], dtype=torch.bool).to(self.gpu_id)
#
#                         time.sleep(2)
#                     elif (val_losses_last_item == bval_loss) and (val_metrics_last_item == bval_metric) and (
#                             val_losses_last_gpu != val_metrics_last_gpu) and (self.gpu_id == val_losses_last_gpu):
#                         print(f"""\t\t1/2:[GPU{self.gpu_id}] val_loss improved to {
#                         val_losses_last_item:.4f} | val_f1score: {val_losses_last_metric:.4f}""")
#                         self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                         improved = torch.tensor([True], dtype=torch.bool).to(self.gpu_id)
#
#                         time.sleep(2)
#                     elif (val_losses_last_item == bval_loss) and (self.gpu_id == val_losses_last_gpu):
#                         print(f"""\t\t1/3:[GPU{self.gpu_id}] val_loss improved to {
#                         val_losses_last_item:.4f} | val_f1score: {val_losses_last_metric:.4f}""")
#                         self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                         improved = torch.tensor([True], dtype=torch.bool).to(self.gpu_id)
#
#                         time.sleep(2)
#                     # elif (val_metrics_last_item == bval_metric) and (self.gpu_id == val_metrics_last_gpu):
#                     #     print(f"""\t\t1/4[GPU{self.gpu_id}] val_loss: {
#                     #     val_metrics_last_loss:.4f} | val_f1score improved to {val_metrics_last_item:.4f}""")
#                     #     self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                     #     improved = torch.tensor([True], dtype=torch.bool).to(self.gpu_id)
#
#                     #     time.sleep(2)
#                 elif (len(torch.where(val_losses_t == val_losses_last_item)[1]) == 1) and (
#                         len(torch.where(val_metrics_t == val_metrics_last_item)[1]) > 1):
#                     val_losses_last_gpu = torch.where(
#                         val_losses_t == val_losses_last_item)[1].item()
#                     val_losses_last_gpu_row = torch.where(
#                         val_losses_t == val_losses_last_item)[0].item()
#                     val_losses_last_metric = val_metrics_t[val_losses_last_gpu_row, val_losses_last_gpu]
#
#                     if (val_losses_last_item == bval_loss) and (self.gpu_id == val_losses_last_gpu):
#                         print(f"""\t\t3:[GPU{self.gpu_id}] val_loss improved to {
#                         val_losses_last_item:.4f} | val_f1score: {val_losses_last_metric:.4f}""")
#                         self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                         improved = torch.tensor([True], dtype=torch.bool).to(self.gpu_id)
#
#                         time.sleep(2)
#                 else:
#                     pass
#             else:
#                 if (val_losses_last_item < best_val_loss) and (val_metrics_last_item > best_val_f1):
#                     print(f"""\t\t1:val_loss improved to {
#                     val_losses_last_item:.4f} | val_f1score improved to {val_metrics_last_item:.4f}""")
#                     self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#                     best_val_loss = val_losses_last_item
#                     best_val_f1 = val_metrics_last_item
#
#                     improved = torch.tensor([True], dtype=torch.bool)
#
#                     time.sleep(2)
#                 elif val_losses_last_item < best_val_loss:
#                     print(f"""\t\t2:val_loss improved to {
#                     val_losses_last_item:.4f} | val_f1score: {val_metrics_last_item:.4f}""")
#                     self._save_checkpoint(epoch, train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#                     best_val_loss = val_losses_last_item
#
#                     improved = torch.tensor([True], dtype=torch.bool)
#
#                     time.sleep(2)
#                 # elif val_metrics_last_item == bval_metric:
#                 #     print(f"""\t\t3:val_loss: {
#                 #     val_losses_last_item:.4f} | val_f1score improved to {val_metrics_last_item:.4f}""")
#                 #     self._save_checkpoint(train_loss, train_accuracy, train_f1, val_loss, val_accuracy, val_f1, train_labels, val_labels)
#
#                 #     improved = torch.tensor([True], dtype=torch.bool)
#
#                 #     time.sleep(2)
#                 else:
#                     pass
#
#             if self.use_gpu:
#                 # Synchronize patience count across all GPU
#                 improved_state = self.gather_tensor(improved)
#
#                 # Update patience count
#                 if self.world_size == 1:
#                     if improved_state:
#                         patience_count.zero_()
#                     else:
#                         patience_count += 1
#                 else:
#                     if (improved_state[0] and improved_state[1]) or (improved_state[0] or improved_state[1]):
#                         patience_count.zero_()
#                     else:
#                         patience_count += 1
#
#                 # Synchronize patience count across all GPUs
#                 all_patience_counts = self.gather_tensor(patience_count)
#                 max_patience_count = torch.max(all_patience_counts).item()
#                 patience_count.fill_(max_patience_count)
#
#                 if max_patience_count >= self.patience:
#                     print(
#                         f"\n[GPU{self.gpu_id}] Patience exceeded. Early stopping...")
#                     should_stop[0] = 1
#
#                 # Synchronize the should_stop tensor across all GPUs
#                 should_stop_list = [torch.zeros(1).to(
#                     self.gpu_id) for _ in range(self.world_size)]
#                 torch.distributed.all_gather(should_stop_list, should_stop)
#
#                 # If any GPU wants to stop, all GPUs should stop
#                 if any(_stop.item() for _stop in should_stop_list):
#                     break
#             else:
#                 if improved:
#                     patience_count.zero_()
#                 else:
#                     patience_count += 1
#
#                     if patience_count >= self.patience:
#                         print(f"\nPatience exceeded. Early stopping...")
#                         break
#
#             time.sleep(2)
#
#         if self.use_gpu:
#             # Ensure all GPUs exit the training loop together
#             dist.barrier()
#
#             if self.gpu_id == 0:
#                 np.save("train_losses.npy", self.train_losses_, allow_pickle=True)
#                 np.save("train_f1s.npy", self.train_f1s_, allow_pickle=True)
#                 np.save("train_accuracies.npy", self.train_accuracies_, allow_pickle=True)
#                 np.save("val_losses.npy", self.val_losses_, allow_pickle=True)
#                 np.save("val_f1s.npy", self.val_f1s_, allow_pickle=True)
#                 np.save("val_accuracies.npy", self.val_accuracies_, allow_pickle=True)
#         else:
#             np.save("train_losses.npy", self.train_losses_, allow_pickle=True)
#             np.save("train_f1s.npy", self.train_f1s_, allow_pickle=True)
#             np.save("train_accuracies.npy", self.train_accuracies_, allow_pickle=True)
#             np.save("val_losses.npy", self.val_losses_, allow_pickle=True)
#             np.save("val_f1s.npy", self.val_f1s_, allow_pickle=True)
#             np.save("val_accuracies.npy", self.val_accuracies_, allow_pickle=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pt_train.py
# from torch.distributed import init_process_group, destroy_process_group
# from pt_engine import CustomTrainer
# from data_loader import load_data_objs
# from typing import Optional
# from pathlib import Path
# import torch.multiprocessing as mp
# import torch.distributed as dist
# import numpy as np
# import argparse
# import random
# import torch
# import time
# import os
#
#
# NUM_WORKERS = os.cpu_count()
#
#
# def find_free_port():
#     """Finds a free port."""
#     import socket
#     with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
#         s.bind(('', 0))  # Bind to port 0 to get a free port
#         print("Got free port...")
#         return s.getsockname()[1]
#
#
# def ddp_setup(rank: int, world_size: int) -> None:
#     """
#     Args:
#         rank: Unique identifier of each process
#         world_size: Total number of processes
#     """
#     os.environ['MASTER_ADDR'] = 'localhost'
#     os.environ['MASTER_PORT'] = '12355'
#     print("Init. process group...")
#     dist.init_process_group("nccl", rank=rank, world_size=world_size)
#     torch.cuda.set_device(rank)
#
#
# def cleanup():
#     dist.destroy_process_group()
#
#
# def set_seed(seed):
#     random.seed(seed)
#     np.random.seed(seed)
#     torch.manual_seed(seed)
#     if torch.cuda.is_available():
#         torch.cuda.manual_seed(seed)
#         torch.cuda.manual_seed_all(seed)
#
#
# def main(rank: Optional[int], world_size: Optional[int], total_epochs: int, patience: int, batch_size: int, save_path: str | Path, xtrain_path: str, ytrain_path: str, xval_path: str, yval_path: str, in_features: int, learning_rate: float, lr_scheduler: str, use_gpu: bool) -> None:
#     if use_gpu:
#         # if rank == 0:
#         print(f"{'>' * 10}MulticlassClassifier Model Training (GPU){'<' * 10}\n")
#         ddp_setup(rank, world_size)
#     else:
#         print(f"{'>' * 10}MulticlassClassifier Model Training (CPU){'<' * 10}\n")
#
#     print("Initializing dataset and model...")
#     train_dtl, val_dtl, model, criterion, optimizer = load_data_objs(batch_size, rank, world_size, total_epochs, in_features, xtrain_path,
#                                                                                 ytrain_path, xval_path, yval_path, use_gpu, rank, learning_rate, NUM_WORKERS)
#     print("Creating trainer...")
#     trainer = CustomTrainer(model=model, train_data=train_dtl, val_data=val_dtl, criterion=criterion, optimizer=optimizer, gpu_id=rank,
#                             save_path=save_path, use_gpu=use_gpu, patience=patience, max_epochs=total_epochs, world_size=world_size, lr_scheduler=lr_scheduler)
#     print("Starting model training...")
#     trainer.train()
#     if use_gpu:
#         cleanup()
#     print(f"\n<{'=' * 10}Training completed & best model saved{'=' * 10}>\nExiting...")
#
#
# def create_model_path(path_str: str) -> Optional[Path]:
#     try:
#         model_path = Path(path_str)
#         model_path.mkdir(parents=True, exist_ok=True)
#
#         # Check if the directory is writable
#         if not os.access(model_path, os.W_OK):
#             raise PermissionError(f"The directory {model_path} is not writable.")
#
#         return model_path
#
#     except (PermissionError, OSError) as e:
#         print(f"Error creating model path: {e}")
#         return None
#
#     except Exception as e:
#         print(f"An unexpected error occurred: {e}")
#         return None
#
#
# def exec_time(st: float, et: float) -> None:
#     hour = int(et-st)//3600
#     minute = int((et-st)%3600)//60
#     second = int(et-st)%60
#     print(f'\nexec time => {hour:02d}hr : {minute:02d}min : {second:02d}sec')
#
#
# if __name__ == "__main__":
#     os.environ['NOTEBOOKAPP_IOPUB_MSG_RATE_LIMIT'] = '10000.0'
#     os.environ['NOTEBOOKAPP_RATE_LIMIT_WINDOW'] = '10.0'
#     os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
#     parser = argparse.ArgumentParser(description='simple distributed training job')
#     parser.add_argument('--total_epochs', default=10, type=int,
#                         help='Total epochs to train the model (default: 10)')
#     parser.add_argument('--patience', default=5, type=int,
#                         help='Patience for increasing val_loss (default: 5)')
#     parser.add_argument('--batch_size', default=32, type=int,
#                         help='Input batch size on each device (default: 32)')
#     parser.add_argument('--in_features', default=2, type=int,
#                         help='Number of classes (default: 2)')
#     parser.add_argument('--model_save_path', default='./checkpoints', type=str,
#                         help='Path to save the best model (default: ./checkpoints)')
#     parser.add_argument('--xtrain_path', default='X_train.npy', type=str,
#                         help='Path to X_train pytorch tensor (default: X_train.npy)')
#     parser.add_argument('--ytrain_path', default='y_train.npy', type=str,
#                         help='Path to y_train pytorch tensor (default: y_train.npy)')
#     parser.add_argument('--xval_path', default='X_val.npy', type=str,
#                         help='Path to X_val pytorch tensor (default: X_val.npy)')
#     parser.add_argument('--yval_path', default='y_val.npy', type=str,
#                         help='Path to y_val pytorch tensor (default: y_val.npy)')
#     parser.add_argument('--learning_rate', default=0.001, type=float,
#                         help='Select learning rate (default: 0.001)')
#     parser.add_argument('--lr_scheduler', default=None, type=str,
#                         help='Select learning rate scheduler (default: None)')
#     parser.add_argument('--world_size', default=None, type=int,
#                        help='Pass the number of GPUs to be used for training (default: None(all))')
#     parser.add_argument('--use_gpu', action='store_true', help='Train on GPU (default)')
#     parser.add_argument('--no-gpu', dest='gpu', action='store_false', help='Train on CPU')
#     parser.set_defaults(gpu=True)
#     args = parser.parse_args()
#
#     MODEL_PATH = create_model_path(args.model_save_path)
#
#     if MODEL_PATH is None:
#         print("Failed to create model path. Exiting program.")
#         exit(1)
#
#     if args.use_gpu:
#         if args.world_size == None:
#             world_size = torch.cuda.device_count()
#         elif args.world_size > 1 and torch.cuda.device_count() < args.world_size:
#             print(f"Error: Requested {args.world_size} GPUs but only {torch.cuda.device_count()} are available.")
#             exit(1)
#         else:
#             world_size = args.world_size
#
#         # Set the start method to 'forkserver'
#         mp.set_start_method('forkserver', force=True)
#
#         set_seed(42)
#
#         start_time = time.time()
#         mp.spawn(main,
#                  args=(world_size, args.total_epochs, args.patience, args.batch_size, MODEL_PATH, args.xtrain_path, args.ytrain_path,
#                        args.xval_path, args.yval_path, args.in_features, args.learning_rate, args.lr_scheduler, args.use_gpu), nprocs=world_size, join=True)
#         end_time = time.time()
#         exec_time(start_time, end_time)
#     else:
#         start_time = time.time()
#         set_seed(42)
#         main(None, None, args.total_epochs, args.patience, args.batch_size, MODEL_PATH, args.xtrain_path, args.ytrain_path,
#             args.xval_path, args.yval_path, args.in_features, args.learning_rate, args.lr_scheduler, args.use_gpu)
#         end_time = time.time()
#         exec_time(start_time, end_time)

# !python pt_train.py --total_epochs 10 --batch_size 64 --use_gpu --in_features 19 --xtrain_path '/content/x_train.npy' --ytrain_path '/content/y_train.npy' --xval_path '/content/x_val.npy' --yval_path '/content/y_val.npy' --learning_rate 0.001

# import torchmetrics
# import torch.nn as nn
# from rich.progress import track
# from model_builder import MulticlassClassifier_
# from data_loader import CreateDataset_
# from torch.utils.data import DataLoader

# model = MulticlassClassifier_(classes_num=len(np.unique(y_val))).to(0)
# # print(model)
# criterion = nn.CrossEntropyLoss()
# model_state = torch.load('/content/checkpoints/best_model.pt')
# epoch, model_state_dict, optimizer_state_dict, train_loss, val_loss, train_accuracy, val_accuracy, train_f1score, val_f1score = [model_state[k] for k in model_state.keys()]

# def model_eval(model: nn.Module, criterion: nn.CrossEntropyLoss, xval_path: str, yval_path: str, state_dict: Dict) -> np.ndarray:
#     print(f"\n\n{'>'*10}MulticlassClassifier Model Evaluation{'<'*10}\n")
#     model.load_state_dict(state_dict)
#     Xval = np.load(xval_path, allow_pickle=True)
#     yval = np.load(yval_path, allow_pickle=True)
#     val_dts = CreateDataset_(Xval, yval)
#     val_dtl = DataLoader(val_dts, batch_size=1, shuffle=False, pin_memory=True,)
#     classes_num = len(np.unique(yval))
#     loss_fn = criterion.to(0)
#     model.eval()
#     metric_func = torchmetrics.classification.MulticlassAccuracy(num_classes=classes_num, average="micro", sync_on_compute=False).to(0)
#     pred_labels = np.array([{'targets': [], 'preds': []}])
#     total_loss = 0
#     total_samples_ = 0
#     with torch.inference_mode():
#         for source, targets in track(val_dtl, description=f"Evaluating...", style='red', complete_style='cyan', finished_style='green'):
#             source = source.to(0)
#             targets = targets.to(0)

#             y_logits = model(source)
#             preds = torch.softmax(y_logits, dim=1)
#             preds = torch.argmax(preds, dim=1)
#             loss = criterion(y_logits, targets)

#             batch_size_ = source.size(0)  # Get batch size
#             total_samples_ += batch_size_  # Accumulate total samples

#             metric_func.update(preds, targets)
#             total_loss += loss.item() * batch_size_

#             pred_labels[0]['preds'].extend(preds.detach().cpu().numpy().tolist())
#             pred_labels[0]['targets'].extend(targets.cpu().numpy().tolist())

#     avg_loss = total_loss / total_samples_ * 100
#     accuracy = metric_func.compute() * 100

#     print(f"\nLoss --> {avg_loss:.4f}% | Accuracy --> {accuracy:.4f}%")
#     print(f"\nClassification Report:\n{classification_report(pred_labels[0]['targets'], pred_labels[0]['preds'], target_names=le_y.classes_)}")

#     return pred_labels


# pred_labels = model_eval(model, criterion, '/content/x_val.npy', '/content/y_val.npy', model_state_dict)

# plot_confusion_matrix(pred_labels[0]['targets'], pred_labels[0]['preds'], target_names=le_y.classes_, model_name='MulticlassClassifier', plot_name=None)

# plot_precision_recall_curve(pred_labels[0]['targets'], pred_labels[0]['preds'], target_names=le_y.classes_, model_name='MulticlassClassifier', plot_name=None)

# plot_roc_curve(pred_labels[0]['targets'], pred_labels[0]['preds'], target_names=le_y.classes_, model_name='MulticlassClassifier', plot_name=None)
