# -*- coding: utf-8 -*-
"""PS2_nb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQ75MjZi_wXywlgDC-UyFTLQA5NJF8zY

# Cloud Counselage Machine Learning Internship Live Project

Training a ML model to suggest job role based on academic details and preferences of final year graduation students.

# Importing Libraries & Writing Helper Funcs
"""

# Download required libraries
# !pip install icecream torchmetrics optuna mlflow dagshub

import os
import torch
import pickle
import subprocess
from datetime import datetime
from typing import Any, Tuple

import dagshub
import numpy as np
import optuna
import torch.nn as nn
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff
from icecream import ic
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
)
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import (
    LabelEncoder,
    MinMaxScaler,
    OneHotEncoder,
    StandardScaler,
)
from sklearn.utils.class_weight import compute_class_weight

from evaluation_plots import (
    plot_confusion_matrix,
    plot_precision_recall_curve,
    plot_roc_curve,
)
from mlflow_logging import create_experiment
from pytorch_model_trainer.evaluation_plots import nn_model_plots
from pytorch_model_trainer.model_builder import MulticlassClassifier_
from pytorch_model_trainer.pt_train import model_eval


"""# Task
analyze the csv data and carry out all possible EDA with plotly express. extract important insights. also train random forest model.

## Data loading

Load the dataset from the provided CSV file into a Pandas DataFrame.
"""

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
df = pd.read_csv("PS2_Dataset.csv")
# display(df.head())
ic(df.head())

"""## Data exploration

Explore the loaded dataset to understand its structure and characteristics.
"""

# Dataset Shape
ic(df.shape)

# Data Types
ic(df.dtypes)

# Descriptive Statistics
ic(df.describe())

# Missing Values
ic(df.isnull().sum())

# Distribution of Numerical Variables

numerical_features = df.select_dtypes(include=["number"]).columns
for feature in numerical_features:
    fig = px.histogram(df, x=feature, title=f"Distribution of {feature}")
    fig.show()

"""## Data cleaning

Clean the data by handling potential outliers and inconsistencies. Identify potential outliers in numerical features using box plots.
"""

numerical_features = df.select_dtypes(include=["number"]).columns

for feature in numerical_features:
    fig = px.box(df, y=feature, title=f"Box Plot of {feature}")
    fig.show()

"""
Based on the box plots, we can identify potential outliers in 'Logical quotient rating', 'hackathons', and 'coding skills rating'. We will cap the outliers by replacing them with the upper and lower bounds of the IQR.
"""

df_cleaned = df.copy()

for feature in ["Logical quotient rating", "hackathons", "coding skills rating"]:
    q1 = df_cleaned[feature].quantile(0.25)
    q3 = df_cleaned[feature].quantile(0.75)
    Iqr = q3 - q1
    lower_bound = q1 - 1.5 * Iqr
    upper_bound = q3 + 1.5 * Iqr
    df_cleaned[feature] = df_cleaned[feature].clip(lower_bound, upper_bound)

# display(df_cleaned.head())
ic(df_cleaned.head())

"""## Data visualization

Visualize the cleaned data using Plotly Express to gain insights into the distributions of variables, correlations, and potential relationships between features. Visualize the distribution of numerical features using histograms to understand their skewness and potential outliers.
"""

numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for feature in numerical_features:
    fig = px.histogram(df_cleaned, x=feature, title=f"Distribution of {feature}")
    fig.show()

"""
Create a correlation matrix heatmap to analyze the relationships between numerical features.
"""

correlation_matrix = df_cleaned.select_dtypes(include=["number"]).corr()
fig = ff.create_annotated_heatmap(
    z=correlation_matrix.values,
    x=list(correlation_matrix.columns),
    y=list(correlation_matrix.index),
    annotation_text=np.around(correlation_matrix.values, decimals=2),
    showscale=True,
)
fig.update_layout(title="Correlation Matrix Heatmap")
fig.show()


# Identify pairs of features with strong correlation (e.g., correlation > 0.5)
correlation_threshold = 0.5
for i in range(len(correlation_matrix.columns)):
    for j in range(i + 1, len(correlation_matrix.columns)):
        feature1 = correlation_matrix.columns[i]
        feature2 = correlation_matrix.columns[j]
        correlation = correlation_matrix.loc[feature1, feature2]
        # if abs(correlation) > correlation_threshold:
        fig = px.scatter(
            df_cleaned,
            x=feature1,
            y=feature2,
            title=f"Scatter Plot of {feature1} vs {feature2} (Correlation: {correlation:.2f})",
        )
        fig.show()

"""
Create box plots to compare the distribution of a numerical feature across different categories of a categorical feature.
"""

categorical_features = df_cleaned.select_dtypes(include=["object"]).columns
numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for categorical_feature in categorical_features:
    for numerical_feature in numerical_features:
        fig = px.box(
            df_cleaned,
            x=categorical_feature,
            y=numerical_feature,
            title=f"Box Plot of {numerical_feature} across {categorical_feature}",
        )
        fig.show()

"""
Create violin plots to visualize the distribution of a numerical feature across different categories of a categorical feature, complementing the insights from the box plots.
"""

categorical_features = df_cleaned.select_dtypes(include=["object"]).columns
numerical_features = df_cleaned.select_dtypes(include=["number"]).columns

for categorical_feature in categorical_features:
    for numerical_feature in numerical_features:
        fig = px.violin(
            df_cleaned,
            x=categorical_feature,
            y=numerical_feature,
            title=f"Violin Plot of {numerical_feature} across {categorical_feature}",
        )
        fig.show()

"""
Create a pair plot for a subset of relevant numerical features to explore the relationships and potential clusters within the data.
"""

numerical_features_subset = [
    "Logical quotient rating",
    "hackathons",
    "coding skills rating",
    "public speaking points",
]
fig = px.scatter_matrix(
    df_cleaned,
    dimensions=numerical_features_subset,
    title="Pair Plot of Selected Numerical Features",
    height=850,
)
fig.update_traces(diagonal_visible=False)
fig.show()

"""## Data analysis

Analyze the visualized data to identify potential patterns, trends, and relationships between features. Analyze the visualized data to identify potential patterns, trends, and relationships between features, documenting the observations and insights.
"""


"""## Feature engineering

Prepare the data for model training by performing feature engineering steps, including encoding categorical features and potentially creating new features based on existing ones. Select a target variable, Identify categorical features and encode them using one-hot encoding, and split the data into training and testing sets.
"""

df_cleaned["Suggested Job Role"].unique()

df_cleaned["New Suggested Job Role"] = df_cleaned["Suggested Job Role"].replace(
    {
        "Applications Developer": "Software Development & Engineering",
        "CRM Technical Developer": "Software Development & Engineering",
        "Database Developer": "Software Development & Engineering",
        "Mobile Applications Developer": "Software Development & Engineering",
        "Software Developer": "Software Development & Engineering",
        "Software Engineer": "Software Development & Engineering",
        "Software Quality Assurance (QA) / Testing": "Software Development & Engineering",
        "Network Security Engineer": "IT Infrastructure & Security",
        "Systems Security Administrator": "IT Infrastructure & Security",
        "Technical Support": "Technical Support & User Experience",
        "UX Designer": "Technical Support & User Experience",
        "Web Developer": "Software Development & Engineering",
    }
)

ic(df_cleaned["New Suggested Job Role"].value_counts())

# Select the target variable
target_variable = "New Suggested Job Role"

# Split the data into training and testing sets
X = df_cleaned.drop(columns=[target_variable, "Suggested Job Role"])
y = df_cleaned["New Suggested Job Role"]

# Identify categorical features
# categorical_features = X.select_dtypes(include=['object']).columns

X_train, X_, y_train, y_ = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_, y_, test_size=0.5, stratify=y_, random_state=42
)

le_crts = LabelEncoder()
X_train["certifications"] = le_crts.fit_transform(X_train["certifications"])
X_val["certifications"] = le_crts.transform(X_val["certifications"])
X_test["certifications"] = le_crts.transform(X_test["certifications"])
# X['certifications'] = le_crts.fit_transform(X['certifications'])

le_wkshp = LabelEncoder()
X_train["workshops"] = le_wkshp.fit_transform(X_train["workshops"])
X_val["workshops"] = le_wkshp.transform(X_val["workshops"])
X_test["workshops"] = le_wkshp.transform(X_test["workshops"])
# X['workshops'] = le_wkshp.fit_transform(X['workshops'])

le_rwr = LabelEncoder()
X_train["reading and writing skills"] = le_rwr.fit_transform(
    X_train["reading and writing skills"]
)
X_val["reading and writing skills"] = le_rwr.transform(
    X_val["reading and writing skills"]
)
X_test["reading and writing skills"] = le_rwr.transform(
    X_test["reading and writing skills"]
)
# X['reading and writing skills'] = le_rwr.fit_transform(X['reading and writing skills'])

le_memsc = LabelEncoder()
X_train["memory capability score"] = le_memsc.fit_transform(
    X_train["memory capability score"]
)
X_val["memory capability score"] = le_memsc.transform(X_val["memory capability score"])
X_test["memory capability score"] = le_memsc.transform(
    X_test["memory capability score"]
)
# X['memory capability score'] = le_memsc.fit_transform(X['memory capability score'])

le_intsb = LabelEncoder()
X_train["Interested subjects"] = le_intsb.fit_transform(X_train["Interested subjects"])
X_val["Interested subjects"] = le_intsb.transform(X_val["Interested subjects"])
X_test["Interested subjects"] = le_intsb.transform(X_test["Interested subjects"])
# X['Interested subjects'] = le_intsb.fit_transform(X['Interested subjects'])

le_intca = LabelEncoder()
X_train["interested career area "] = le_intca.fit_transform(
    X_train["interested career area "]
)
X_val["interested career area "] = le_intca.transform(X_val["interested career area "])
X_test["interested career area "] = le_intca.transform(
    X_test["interested career area "]
)
# X['interested career area '] = le_intca.fit_transform(X['interested career area '])

le_tycompt = LabelEncoder()
X_train["Type of company want to settle in?"] = le_tycompt.fit_transform(
    X_train["Type of company want to settle in?"]
)
X_val["Type of company want to settle in?"] = le_tycompt.transform(
    X_val["Type of company want to settle in?"]
)
X_test["Type of company want to settle in?"] = le_tycompt.transform(
    X_test["Type of company want to settle in?"]
)
# X['Type of company want to settle in?'] = le_tycompt.fit_transform(X['Type of company want to settle in?'])

le_intbks = LabelEncoder()
X_train["Interested Type of Books"] = le_intbks.fit_transform(
    X_train["Interested Type of Books"]
)
X_val["Interested Type of Books"] = le_intbks.transform(
    X_val["Interested Type of Books"]
)
X_test["Interested Type of Books"] = le_intbks.transform(
    X_test["Interested Type of Books"]
)
# X['Interested Type of Books'] = le_intbks.fit_transform(X['Interested Type of Books'])

ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False, drop="if_binary")
ohe_cols = [
    "self-learning capability?",
    "Extra-courses did",
    "Taken inputs from seniors or elders",
    "Management or Technical",
    "hard/smart worker",
    "worked in teams ever?",
    "Introvert",
]

Xt_ohe = np.asarray(ohe.fit_transform(X_train[ohe_cols]))
Xv_ohe = np.asarray(ohe.transform(X_val[ohe_cols]))
Xts_ohe = np.asarray(ohe.transform(X_test[ohe_cols]))
# X_ohe = ohe.fit_transform(X[ohe_cols])

Xt_ohe = pd.DataFrame(Xt_ohe, columns=ohe.get_feature_names_out(ohe_cols))
Xv_ohe = pd.DataFrame(Xv_ohe, columns=ohe.get_feature_names_out(ohe_cols))
Xts_ohe = pd.DataFrame(Xts_ohe, columns=ohe.get_feature_names_out(ohe_cols))
# X_ohe = pd.DataFrame(X_ohe, columns=ohe.get_feature_names_out(ohe_cols))

X_train = pd.concat(
    [X_train.drop(columns=ohe_cols).reset_index(drop=True), Xt_ohe], axis=1
)
X_val = pd.concat([X_val.drop(columns=ohe_cols).reset_index(drop=True), Xv_ohe], axis=1)
X_test = pd.concat(
    [X_test.drop(columns=ohe_cols).reset_index(drop=True), Xts_ohe], axis=1
)
# X_train = pd.concat([X.drop(columns=ohe_cols).reset_index(drop=True), X_ohe], axis=1)

y_train = y_train.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)
# yn = y.reset_index(drop=True)

X_train["Technical_Inclination"] = (
    X_train["Logical quotient rating"]
    + X_train["coding skills rating"]
    + X_train["Interested subjects"]
)
X_val["Technical_Inclination"] = (
    X_val["Logical quotient rating"]
    + X_val["coding skills rating"]
    + X_val["Interested subjects"]
)
X_test["Technical_Inclination"] = (
    X_test["Logical quotient rating"]
    + X_test["coding skills rating"]
    + X_test["Interested subjects"]
)

X_train["Teamwork_Comm_Aptitude"] = (
    X_train["public speaking points"]
    + X_train["reading and writing skills"]
    + (X_train["worked in teams ever?_yes"] * 2)
)
X_val["Teamwork_Comm_Aptitude"] = (
    X_val["public speaking points"]
    + X_val["reading and writing skills"]
    + (X_val["worked in teams ever?_yes"] * 2)
)
X_test["Teamwork_Comm_Aptitude"] = (
    X_test["public speaking points"]
    + X_test["reading and writing skills"]
    + (X_test["worked in teams ever?_yes"] * 2)
)

X_train["Proactive_Learning"] = (
    (X_train["self-learning capability?_yes"] * 2)
    + (X_train["Extra-courses did_yes"] * 1.5)
    + X_train["certifications"]
    + X_train["workshops"]
)
X_val["Proactive_Learning"] = (
    (X_val["self-learning capability?_yes"] * 2)
    + (X_val["Extra-courses did_yes"] * 1.5)
    + X_val["certifications"]
    + X_val["workshops"]
)
X_test["Proactive_Learning"] = (
    (X_test["self-learning capability?_yes"] * 2)
    + (X_test["Extra-courses did_yes"] * 1.5)
    + X_test["certifications"]
    + X_test["workshops"]
)

X_train["Company_Fit"] = (
    X_train["Type of company want to settle in?"]
    + X_train["hard/smart worker_smart worker"]
)
X_val["Company_Fit"] = (
    X_val["Type of company want to settle in?"]
    + X_val["hard/smart worker_smart worker"]
)
X_test["Company_Fit"] = (
    X_test["Type of company want to settle in?"]
    + X_test["hard/smart worker_smart worker"]
)

X_train["Experience_Exposure"] = X_train["hackathons"] + X_train["coding skills rating"]
X_val["Experience_Exposure"] = X_val["hackathons"] + X_val["coding skills rating"]
X_test["Experience_Exposure"] = X_test["hackathons"] + X_test["coding skills rating"]

le_y = LabelEncoder()
y_train_encoded = le_y.fit_transform(y_train)

# Compute class weights using encoded labels
class_weights = compute_class_weight(
    class_weight="balanced", classes=np.unique(y_train_encoded), y=y_train_encoded
)

# Create dictionary with numeric indices
class_weight_dict = {idx: weight for idx, weight in enumerate(class_weights)}
# class_weight_dict[0] = class_weight_dict[0] * 1
class_weight_dict[1] = class_weight_dict[1] * 0.5
# class_weight_dict[2] = class_weight_dict[2] * 1

# Save all artifacts
artifacts_path = "assets/artifacts"
# os.makedirs(artifacts_path, exist_ok=True)
artifact_files = {
    "le_crts/le_crts.sav": le_crts,
    "le_intbks/le_intbks.sav": le_intbks,
    "le_intca/le_intca.sav": le_intca,
    "le_intsb/le_intsb.sav": le_intsb,
    "le_memsc/le_memsc.sav": le_memsc,
    "le_rwr/le_rwr.sav": le_rwr,
    "le_tycompt/le_tycompt.sav": le_tycompt,
    "le_wkshp/le_wkshp.sav": le_wkshp,
    "ohe/one_hot_encoder.sav": ohe,
    "ohe_cols/ohe_cols.sav": ohe_cols,
    "le_y/le_y.sav": le_y,
}

for filepath, obj in artifact_files.items():
    dir_path = artifacts_path + "/" + filepath.split("/")[0]
    os.makedirs(dir_path, exist_ok=True)
    full_path = os.path.join(dir_path, filepath.split("/")[1])
    # if not os.path.exists(full_path):
    #     raise FileNotFoundError(f"Artifact file not found: {full_path}")
    with open(full_path, "wb") as f:
        pickle.dump(obj, f)

df_corr = pd.DataFrame(pd.concat([X_train, pd.Series(y_train)], axis=1))
df_corr = df_corr.rename(columns={df_corr.columns[-1]: "new job roles"})

correlation_matrix = df_corr.select_dtypes(include=["number"]).corr()

# Get correlation values for the last index ('new job roles')
correlation_with_target = np.array(
    # Reshape to 2D array
    correlation_matrix.iloc[-1, :-1].values
).reshape(1, -1)
# Get feature names for x-axis labels
feature_names = correlation_matrix.columns[:-1].tolist()

fig = ff.create_annotated_heatmap(
    z=correlation_with_target,
    x=feature_names,
    y=["new job roles"],
    annotation_text=np.around(correlation_with_target, decimals=2),
    showscale=True,
    colorscale="Viridis",
)
fig.update_layout(title="Correlation of Target Variable with other Features")
fig.show()

selector = SelectKBest(chi2, k=10)
selector.fit(X_train, y_train)
selected_features = X_train.columns[selector.get_support()]
ic(selected_features)

# pd.DataFrame(data=[selector.feature_names_in_, selector.scores_], index=['Features', 'Scores']).T.sort_values(by='Scores', ascending=False)
ic(
    pd.DataFrame(
        data=[selector.feature_names_in_, selector.scores_],
        index=["Features", "Scores"],
    ).T.sort_values(by="Scores", ascending=False),
)

X_train = X_train[selected_features]
ic(X_train)

# Xt_sampled, yt_sampled = X_train[selected_features].copy(deep=True), pd.Series(y_train.copy(deep=True))

under = RandomUnderSampler(
    sampling_strategy="majority",
    #  {
    #      'IT Infrastructure & Security': 920,
    #      'Software Development & Engineering': 920,  # Limit the majority class
    #      'Technical Support & User Experience': 920,
    #      }
    random_state=42,
    replacement=True,
)

Xt_sampled, yt_sampled = under.fit_resample(X_train, y_train)  # type: ignore
ic(yt_sampled.value_counts())

# Get feature importances from the Random Forest model
rf_model = RandomForestClassifier()
rf_model.fit(Xt_sampled, yt_sampled)
feature_importances = pd.Series(rf_model.feature_importances_, index=Xt_sampled.columns)

# Sort feature importances in descending order
feature_importances = feature_importances.sort_values(ascending=False)

# Print the top 10 most important features
# display(feature_importances)
ic(feature_importances)

"""## Model Training

### Setting DAGsHub & MLFlow
"""

# from google.colab import userdata
# REPO_OWNER_ = userdata.get('REPO_OWNER')
# REPO_NAME_ = userdata.get('REPO_NAME')
# TRACKING_URI = userdata.get('MLFLOW_TRACKING_URI')

REPO_OWNER_ = os.environ.get("REPO_OWNER")
REPO_NAME_ = os.environ.get("REPO_NAME")
TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI")

os.makedirs("tmp", exist_ok=True)

# Creating function to log experiments to mlflow
dagshub.init(repo_owner=REPO_OWNER_, repo_name=REPO_NAME_, mlflow=True)  # type: ignore


"""### Optuna"""


# Define the evaluation function
def evaluate_model(
    y_true: Any, y_pred: Any
) -> Tuple[float, float, float, float, float, float]:
    # y_true = np.asarray(y_true)
    # y_pred = np.asarray(y_pred)
    accuracy = float(accuracy_score(y_true, y_pred))
    precision = float(precision_score(y_true, y_pred, average="macro"))
    recall = float(recall_score(y_true, y_pred, average="macro"))
    balanced_acc = balanced_accuracy_score(y_true, y_pred)
    mcc = matthews_corrcoef(y_true, y_pred)
    f1 = float(f1_score(y_true, y_pred, average="macro"))
    return accuracy, precision, recall, balanced_acc, mcc, f1


# Random Forest with Optuna
def objective_rf(trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 500),
        "max_depth": trial.suggest_int("max_depth", 20, 60),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2"]),
        "min_samples_split": trial.suggest_int("min_samples_split", 20, 50),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 20, 50),
        "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        "class_weight": trial.suggest_categorical(
            "class_weight", ["balanced_subsample", "balanced"]
        ),
        # 'class_weight': class_weight_dict,
        "random_state": 42,
        "n_jobs": -1,
    }

    # Use stratified k-fold CV
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

    pipeline = make_pipeline(
        # StandardScaler(),
        MinMaxScaler(),
        RandomForestClassifier(**params),
    )

    # Calculate cross-validation score (accuracy)
    scores = []
    for train_idx, val_idx in cv.split(Xt_sampled.to_numpy(), yt_sampled.to_numpy()):
        X_fold_train = Xt_sampled.iloc[train_idx]
        X_fold_val = Xt_sampled.iloc[val_idx]
        y_fold_train = yt_sampled.iloc[train_idx]
        y_fold_val = yt_sampled.iloc[val_idx]

        pipeline.fit(X_fold_train, y_fold_train)
        y_pred = pipeline.predict(X_fold_val)
        # fold_f1 = f1_score(y_fold_val, y_pred, average='macro')
        _, _, _, accuracy, _, _ = evaluate_model(y_fold_val.to_numpy(), y_pred)
        scores.append(accuracy)

    # pipeline.fit(Xt_sampled, yn)
    # y_pred = pipeline.predict(X_val)
    # _, _, _, accuracy, _, _ = evaluate_model(y_val, y_pred)

    return float(np.mean(scores))  # Return the mean accuracy across folds
    # return accuracy


# Run optimization for each model
np.random.seed(42)
study_rf = optuna.create_study(direction="maximize")
study_rf.optimize(objective_rf, n_trials=20, n_jobs=-1)

best_params3 = study_rf.trials_dataframe().sort_values(ascending=False, by="value")

# Random Forest
best_rf = make_pipeline(
    StandardScaler(),
    RandomForestClassifier(
        n_estimators=best_params3.iloc[0]["params_n_estimators"],
        max_depth=best_params3.iloc[0]["params_max_depth"],
        max_features=best_params3.iloc[0]["params_max_features"],
        min_samples_split=best_params3.iloc[0]["params_min_samples_split"],
        min_samples_leaf=best_params3.iloc[0]["params_min_samples_leaf"],
        bootstrap=best_params3.iloc[0]["params_bootstrap"],
        class_weight=best_params3.iloc[0]["params_class_weight"],
        # class_weight=class_weight_dict,
        random_state=42,
        n_jobs=-1,
    ),
)

Xv = X_val[selected_features]
best_rf.fit(Xt_sampled, yt_sampled)
print("\n\nRandom Forest Classifier | Training:")
print(f"Train set Score: {best_rf.score(Xt_sampled, yt_sampled):.4f}")
print(f"Val set Score: {best_rf.score(Xv, y_val):.4f}")
y_train_rf = best_rf.predict(Xt_sampled)
y_pred_rf = best_rf.predict(Xv)

(
    train_accuracy_rf,
    train_precision_rf,
    train_recall_rf,
    train_bacc_rf,
    train_mcc_rf,
    train_f1_rf,
) = evaluate_model(yt_sampled, y_train_rf)
val_accuracy_rf, val_precision_rf, val_recall_rf, val_bacc_rf, val_mcc_rf, val_f1_rf = (
    evaluate_model(y_val, y_pred_rf)
)

# print("Random Forest Classifier:")
print(f"Best parameters: {study_rf.best_params}")
print(
    f"Train | Accuracy: {train_accuracy_rf:.4f}, Precision: {train_precision_rf:.4f}, Recall: {train_recall_rf:.4f}, Balance Acc: {train_bacc_rf:.4f}, MCC: {train_mcc_rf:.4f}, F1-score: {train_f1_rf:.4f}"
)
print(
    f"Val | Accuracy: {val_accuracy_rf:.4f}, Precision: {val_precision_rf:.4f}, Recall: {val_recall_rf:.4f}, Balance Acc: {val_bacc_rf:.4f}, MCC: {val_mcc_rf:.4f}, F1-score: {val_f1_rf:.4f}"
)

print(
    f"\nTrain | Classification Report for Random Forest Classifier:\n{classification_report(yt_sampled, y_train_rf, target_names=np.unique(yt_sampled))}"
)
print(
    f"\nVal | Classification Report for Random Forest Classifier:\n{classification_report(y_val, y_pred_rf, target_names=np.unique(yt_sampled))}"
)

plot_confusion_matrix(
    y_val,
    y_pred_rf,
    target_names=le_y.classes_,
    model_name="MulticlassClassifier",
    plot_name="jrs_val_cm.html",
)

plot_precision_recall_curve(
    np.asarray(le_y.transform(y_val)),
    np.asarray(le_y.transform(y_pred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_val_prcurve.html",
)

plot_roc_curve(
    np.asarray(le_y.transform(y_val)),
    np.asarray(le_y.transform(y_pred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_val_roccurve.html",
)

Xts = X_test[selected_features]
y_tspred_rf = best_rf.predict(Xts)
(
    test_accuracy_rf,
    test_precision_rf,
    test_recall_rf,
    test_bacc_rf,
    test_mcc_rf,
    test_f1_rf,
) = evaluate_model(y_test, y_tspred_rf)

print("Random Forest Classifier | Testing:")
print(f"Best parameters: {study_rf.best_params}")
print(
    f"Train | Accuracy: {train_accuracy_rf:.4f}, Precision: {train_precision_rf:.4f}, Recall: {train_recall_rf:.4f}, Balance Acc: {train_bacc_rf:.4f}, MCC: {train_mcc_rf:.4f}, F1-score: {train_f1_rf:.4f}"
)
print(
    f"Test | Accuracy: {test_accuracy_rf:.4f}, Precision: {test_precision_rf:.4f}, Recall: {test_recall_rf:.4f}, Balance Acc: {test_bacc_rf:.4f}, MCC: {test_mcc_rf:.4f}, F1-score: {test_f1_rf:.4f}"
)

print(
    f"\nTrain | Classification Report for Random Forest Classifier:\n{classification_report(yt_sampled, y_train_rf, target_names=np.unique(y))}"
)
print(
    f"\nTest | Classification Report for Random Forest Classifier:\n{classification_report(y_test, y_tspred_rf, target_names=np.unique(y))}"
)

plot_confusion_matrix(
    y_test,
    y_tspred_rf,
    target_names=le_y.classes_,
    model_name="MulticlassClassifier",
    plot_name="jrs_test_cm.html",
)

plot_precision_recall_curve(
    np.asarray(le_y.transform(y_test)),
    np.asarray(le_y.transform(y_tspred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_test_prcurve.html",
)

plot_roc_curve(
    np.asarray(le_y.transform(y_test)),
    np.asarray(le_y.transform(y_tspred_rf)),
    le_y.classes_,
    "MulticlassClassifier",
    "jrs_test_roccurve.html",
)

"""#### Logging Experiment"""

# Logging Experiment

experiment_name = "job_role_suggestion"
run_name = "run_" + str(datetime.now().strftime("%d-%m-%y_%H:%M:%S"))

run_metrics = {
    "train_acc": train_accuracy_rf,
    "test_acc": test_accuracy_rf,
    "train_precision": train_precision_rf,
    "test_precision": test_precision_rf,
    "train_recall": train_recall_rf,
    "test_recall": test_recall_rf,
    "train_f1": train_f1_rf,
    "test_f1": test_f1_rf,
    "train_bal_acc": train_bacc_rf,
    "test_bal_acc": test_bacc_rf,
    "train_mcc": train_mcc_rf,
    "test_mcc": test_mcc_rf,
    "val_acc": val_accuracy_rf,
    "val_precision": val_precision_rf,
    "val_recall": val_recall_rf,
    "val_bal_acc": val_bacc_rf,
    "val_mcc": val_mcc_rf,
    "val_f1": val_f1_rf,
}

artifact_paths = {
    "le_crts": "assets/artifacts/le_crts/le_crts.sav",
    "le_intbks": "assets/artifacts/le_intbks/le_intbks.sav",
    "le_intca": "assets/artifacts/le_intca/le_intca.sav",
    "le_intsb": "assets/artifacts/le_intsb/le_intsb.sav",
    "le_memsc": "assets/artifacts/le_memsc/le_memsc.sav",
    "le_rwr": "assets/artifacts/le_rwr/le_rwr.sav",
    "le_tycompt": "assets/artifacts/le_tycompt/le_tycompt.sav",
    "le_wkshp": "assets/artifacts/le_wkshp/le_wkshp.sav",
    "ohe": "assets/artifacts/ohe/one_hot_encoder.sav",
    "ohe_cols": "assets/artifacts/ohe_cols/ohe_cols.sav",
    "le_y": "assets/artifacts/le_y/le_y.sav",
    "val_cm": "plotly_html/jrs_val_cm.html",
    "val_prcurve": "plotly_html/jrs_val_prcurve.html",
    "val_roccurve": "plotly_html/jrs_val_roccurve.html",
    "test_cm": "plotly_html/jrs_test_cm.html",
    "test_prcurve": "plotly_html/jrs_test_prcurve.html",
    "test_roccurve": "plotly_html/jrs_test_roccurve.html",
}

run_params = study_rf.best_params

create_experiment(
    experiment_name,
    run_name,
    run_metrics,
    best_rf,
    model_name="job_role_rf",
    TRACKING_URI=TRACKING_URI,  # type: ignore
    artifact_paths=artifact_paths,
    run_params=run_params,
    tag_dict={"tag1": "Random Forest Classifier", "tag2": "Job Role Suggestion"},
)

"""### NN Model"""

nny_train = le_y.fit_transform(yt_sampled)
nny_val = le_y.transform(y_val)
nny_test = le_y.transform(y_test)

np.save("assets/x_train.npy", Xt_sampled, allow_pickle=True)
np.save("assets/y_train.npy", nny_train, allow_pickle=True)
np.save("assets/x_val.npy", X_val, allow_pickle=True)
np.save("assets/y_val.npy", nny_val, allow_pickle=True)
np.save("assets/x_test.npy", X_test, allow_pickle=True)
np.save("assets/y_test.npy", nny_test, allow_pickle=True)


# Run pytorch_model_trainer/pt_train.py with arguments
# Command line method
# !python pt_train.py --total_epochs 10 --batch_size 64 --use_gpu --learning_rate 0.001

# Python subprocess method
# Set environment variable for Colab
os.environ["COLAB_BACKEND"] = "1"
MODEL_PATH: str = "./checkpoints"

cmd = [
    "python",
    "pytorch_model_trainer/pt_train.py",
    "--total_epochs",
    "10",
    "--batch_size",
    "64",
    "--model_save_path",
    MODEL_PATH,
    "--use_gpu",
    "--learning_rate",
    "0.001",
]


try:
    process = subprocess.run(cmd, check=True, env=dict(os.environ, PYTHONPATH="."))
    # Capture stdout and stderr
    process = subprocess.run(cmd, check=True, capture_output=True, text=True)
    print("Subprocess finished successfully.")
    print("Stdout:\n", process.stdout)
except subprocess.CalledProcessError as e:
    print(f"Subprocess failed with exit code {e.returncode}")
    print("Stderr:\n", e.stderr)
    print("Stdout:\n", e.stdout)  # Also print stdout for potential debugging
except Exception as e:
    print(f"An unexpected error occurred: {e}")
finally:
    print("Subprocess finished.")


# Preparing data for plotting epochs vs metrics curve.
saved_metrics = np.load(
    "assets/training_metrics.npy", allow_pickle=True).item()
saved_metrics = pd.concat(
    [
        pd.DataFrame(saved_metrics["train_losses"]),
        pd.DataFrame(saved_metrics["val_losses"]),
        pd.DataFrame(saved_metrics["train_f1s"]),
        pd.DataFrame(saved_metrics["val_f1s"]),
        pd.DataFrame(saved_metrics["train_accuracies"]),
        pd.DataFrame(saved_metrics["val_accuracies"]),
    ],
    axis=1,
)
saved_metrics["epochs"] = np.arange(1, len(saved_metrics) + 1)

figures = nn_model_plots(saved_metrics)
# if len(figures) == 6:
#     fig1, fig2, fig3, fig4, fig5, fig6 = figures
#     fig1.show()
#     fig2.show()
#     fig3.show()
#     fig4.show()
#     fig5.show()
#     fig6.show()
# else:
#     fig1, fig2, fig3 = figures
#     fig1.show()
#     fig2.show()
#     fig3.show()

# Initializing nn model for evaluation
x_train = np.load("assets/x_train.npy", allow_pickle=True)
nny_train = np.load("assets/y_train.npy", allow_pickle=True)
model = MulticlassClassifier_(
    classes_num=len(np.unique(nny_train)), in_features=x_train.shape[1]
).to(0)
criterion = nn.CrossEntropyLoss()
model_state = torch.load(
    os.path.join(MODEL_PATH, "best_model.pt"), weights_only=False
)
(
    epoch,
    model_state_dict,
    optimizer_state_dict,
    train_loss,
    val_loss,
    train_accuracy,
    val_accuracy,
    train_f1score,
    val_f1score,
    train_labels,
    val_labels,
) = [model_state[k] for k in model_state.keys()]

print(f"\n\n\n{'>' * 10}MulticlassClassifier Model Evaluation{'<' * 10}\n")

# Training set prediction
print("\n\nTraining Set Prediction:")
(
    pred_train_labels,
    avgloss,
    pred_train_acc,
    pred_train_f1s,
    pred_train_bacc,
    pred_train_precision,
    pred_train_recall,
    pred_train_mcc,
) = model_eval(
    model, criterion, "assets/x_train.npy", "assets/y_train.npy", model_state_dict
)

train_cm = plot_confusion_matrix(
    pred_train_labels[0]["targets"],
    pred_train_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Training Set",
    plot_name="jrs_nn_train_cm.html",
)
# train_cm.show()

train_prc = plot_precision_recall_curve(
    pred_train_labels[0]["targets"],
    pred_train_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Training Set",
    plot_name="jrs_nn_train_prcurve.html",
)
# train_prc.show()

train_roc = plot_roc_curve(
    pred_train_labels[0]["targets"],
    pred_train_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Training Set",
    plot_name="jrs_nn_train_roccurve.html",
)
# train_roc.show()

# Validation set prediction
print("\n\nValidation Set Prediction:")
(
    pred_val_labels,
    avgloss,
    pred_val_acc,
    pred_val_f1s,
    pred_val_bacc,
    pred_val_precision,
    pred_val_recall,
    pred_val_mcc,
) = model_eval(
    model, criterion, "assets/x_val.npy", "assets/y_val.npy", model_state_dict
)

val_cm = plot_confusion_matrix(
    pred_val_labels[0]["targets"],
    pred_val_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Validation Set",
    plot_name="jrs_nn_val_cm.html",
)
# val_cm.show()

val_prc = plot_precision_recall_curve(
    pred_val_labels[0]["targets"],
    pred_val_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Validation Set",
    plot_name="jrs_nn_val_prcurve.html",
)
# val_prc.show()

val_roc = plot_roc_curve(
    pred_val_labels[0]["targets"],
    pred_val_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Validation Set",
    plot_name="jrs_nn_val_roccurve.html",
)
# val_roc.show()

# Testing set prediction
print("\n\nTesting Set Prediction:")
(
    pred_test_labels,
    avgloss,
    pred_test_acc,
    pred_test_f1s,
    pred_test_bacc,
    pred_test_precision,
    pred_test_recall,
    pred_test_mcc,
) = model_eval(
    model, criterion, "assets/x_test.npy", "assets/y_test.npy", model_state_dict
)

test_cm = plot_confusion_matrix(
    pred_test_labels[0]["targets"],
    pred_test_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Test Set",
    plot_name="jrs_nn_test_cm.html",
)
# test_cm.show()

test_prc = plot_precision_recall_curve(
    pred_test_labels[0]["targets"],
    pred_test_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Test Set",
    plot_name="jrs_nn_test_prcurve.html",
)
# test_prc.show()

test_roc = plot_roc_curve(
    pred_test_labels[0]["targets"],
    pred_test_labels[0]["preds"],
    target_names=le_y.classes_,
    model_name="MulticlassClassifier on Test Set",
    plot_name="jrs_nn_test_roccurve.html",
)
# test_roc.show()


"""#### Logging Experiment"""
# Logging Experiment
experiment_name = "job_role_suggestion"
run_name = "run_" + str(datetime.now().strftime("%d-%m-%y_%H:%M:%S"))
run_metrics = {
    "train_acc": pred_train_acc,
    "test_acc": pred_test_acc,
    "train_precision": pred_train_precision,
    "test_precision": pred_test_precision,
    "train_recall": pred_train_recall,
    "test_recall": pred_test_recall,
    "train_f1": pred_train_f1s,
    "test_f1": pred_test_f1s,
    "train_bal_acc": pred_train_bacc,
    "test_bal_acc": pred_test_bacc,
    "train_mcc": pred_train_mcc,
    "test_mcc": pred_test_mcc,
    "val_acc": pred_val_acc,
    "val_precision": pred_val_precision,
    "val_recall": pred_val_recall,
    "val_bal_acc": pred_val_bacc,
    "val_mcc": pred_val_mcc,
    "val_f1": pred_val_f1s,
}
artifact_paths = {
    "le_crts": "assets/artifacts/le_crts/le_crts.sav",
    "le_intbks": "assets/artifacts/le_intbks/le_intbks.sav",
    "le_intca": "assets/artifacts/le_intca/le_intca.sav",
    "le_intsb": "assets/artifacts/le_intsb/le_intsb.sav",
    "le_memsc": "assets/artifacts/le_memsc/le_memsc.sav",
    "le_rwr": "assets/artifacts/le_rwr/le_rwr.sav",
    "le_tycompt": "assets/artifacts/le_tycompt/le_tycompt.sav",
    "le_wkshp": "assets/artifacts/le_wkshp/le_wkshp.sav",
    "ohe": "assets/artifacts/ohe/one_hot_encoder.sav",
    "ohe_cols": "assets/artifacts/ohe_cols/ohe_cols.sav",
    "le_y": "assets/artifacts/le_y/le_y.sav",
    "train_cm": "plotly_html/jrs_nn_train_cm.html",
    "train_prcurve": "plotly_html/jrs_nn_train_prcurve.html",
    "train_roccurve": "plotly_html/jrs_nn_train_roccurve.html",
    "val_cm": "plotly_html/jrs_nn_val_cm.html",
    "val_prcurve": "plotly_html/jrs_nn_val_prcurve.html",
    "val_roccurve": "plotly_html/jrs_nn_val_roccurve.html",
    "test_cm": "plotly_html/jrs_nn_test_cm.html",
    "test_prcurve": "plotly_html/jrs_nn_test_prcurve.html",
    "test_roccurve": "plotly_html/jrs_nn_test_roccurve.html",
    "loss_curves_gpu": "plotly_html/loss_curves_gpu.html",
    "acc_curves_gpu": "plotly_html/acc_curves_gpu.html",
    "f1s_curves_gpu": "plotly_html/f1s_curves_gpu.html",
    "model_chkpt": "checkpoints/best_model.pt",
    "model_builder": "pytorch_model_trainer/model_builder.py",
}
run_params = {
    "total_epochs": 10,
    "batch_size": 64,
    "use_gpu": True,
    "in_features": x_train.shape[1],
    "learning_rate": 0.001,
}

# Colab Logging
# REPO_OWNER_ = userdata.get('REPO_OWNER')
# REPO_NAME_ = userdata.get('REPO_NAME')
# TRACKING_URI = userdata.get('MLFLOW_TRACKING_URI')

# Local Logging
# REPO_OWNER_ = os.environ.get("REPO_OWNER")
# REPO_NAME_ = os.environ.get("REPO_NAME")
TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI")

create_experiment(
    experiment_name,
    run_name,
    run_metrics,
    model,
    model_name="job_role_nn",
    TRACKING_URI=TRACKING_URI,  # type: ignore
    artifact_paths=artifact_paths,
    run_params=run_params,
    tag_dict={"tag1": "Neural Network Classifier",
              "tag2": "Job Role Suggestion"},
)
